### ISSUE TITLE
AElf.OS.Rpc.ChainController.Tests.ChainControllerRpcServiceServerTest.Wallet_SignHash_Success

### ISSUE THREAD

**Issue by loning** [AElfProject/AElf#1193]
rror Message:
 System.Exception : Exception while SignWithPrivateKey
---- System.ArgumentException : secretKey must be 32 bytes
Stack Trace:
   at AElf.Cryptography.CryptoHelpers.SignWithPrivateKey(Byte[] privateKey, Byte[] hash) in /home/travis/build/AElfProject/AElf/AElf.Cryptography/CryptoHelpers.cs:line 67
   at AElf.OS.Rpc.Wallet.WalletRpcService.SignHash(String address, String password, String hash) in /home/travis/build/AElfProject/AElf/AElf.OS.Rpc.Wallet/WalletRpcService.cs:line 52
   at CallSite.Target(Closure , CallSite , Object )
   at Anemonis.AspNetCore.JsonRpc.JsonRpcServiceHandler`1.HandleAsync(JsonRpcRequest request)
   at Anemonis.AspNetCore.JsonRpc.JsonRpcMiddleware`1.CreateJsonRpcResponseAsync(HttpContext context, JsonRpcMessageInfo`1 requestInfo)
   at Anemonis.AspNetCore.JsonRpc.JsonRpcMiddleware`1.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at AElf.OS.Rpc.RpcTestBase.JsonCallAsync(String path, String method, Object params, Object id) in /home/travis/build/AElfProject/AElf/AElf.OS.Rpc.TestBase/RpcTestBase.cs:line 69
   at AElf.OS.Rpc.RpcTestBase.JsonCallAsStringAsync(String path, String method, Object params, Object id) in /home/travis/build/AElfProject/AElf/AElf.OS.Rpc.TestBase/RpcTestBase.cs:line 84
   at AElf.OS.Rpc.RpcTestBase.JsonCallAsJObject(String path, String method, Object params, Object id) in /home/travis/build/AElfProject/AElf/AElf.OS.Rpc.TestBase/RpcTestBase.cs:line 91
   at AElf.OS.Rpc.ChainController.Tests.ChainControllerRpcServiceServerTest.Wallet_SignHash_Success() in /home/travis/build/AElfProject/AElf/AElf.OS.Rpc.ChainController.Tests/ChainControllerRpcServiceTest.cs:line 495
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Secp256k1Net.Secp256k1.SignRecoverable(Span`1 signatureOutput, Span`1 messageHash, Span`1 secretKey) in /home/teamcity/BuildAgent/work/4af87a9fd4909eba/Secp256k1.Net/Secp256k1.cs:line 197
   at AElf.Cryptography.CryptoHelpers.SignWithPrivateKey(Byte[] privateKey, Byte[] hash) in /home/travis/build/AElfProject/AElf/AElf.Cryptography/CryptoHelpers.cs:line 60
Standard Output Messages:
 [2019-03-13 13:27:18Z] info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
       Request starting HTTP/2.0 POST http://localhost/chain application/json 
 [2019-03-13 13:27:18Z] info: Anemonis.AspNetCore.JsonRpc.JsonRpcMiddleware[2010]
       0HLL7MUCB16VR JSON-RPC request "e04df5dc-eb70-4e10-a450-a24589979ff5" to the method "BroadcastTransactions" processed with result
 [2019-03-13 13:27:18Z] info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
       Request finished in 2.0806ms 200 application/json
 [2019-03-13 13:27:18Z] info: AElf.Kernel.Services.MinerService[0]
       Generated { hash: 180203c2d193165fa5f3702ec10bcd484e8c65c49d58891d48f9a0e2956e0be9, height: 2, previous: "4aeb7f989a04e3d067a1921732f13ba1f7cc854f4344195fcdf14cbec803b08c", tx-count: 1,duration: 23 ms. }
 [2019-03-13 13:27:18Z] info: AElf.Kernel.SmartContractExecution.Application.FullBlockchainExecutingService[0]
       Executed block "180203c2d193165fa5f3702ec10bcd484e8c65c49d58891d48f9a0e2956e0be9" at height 2.
 [2019-03-13 13:27:18Z] info: AElf.Kernel.SmartContractExecution.Application.FullBlockchainExecutingService[0]
       Longest chain execution duration: 2 ms, status LongestChainFound, best chain "180203c2d193165fa5f3702ec10bcd484e8c65c49d58891d48f9a0e2956e0be9"
 [2019-03-13 13:27:18Z] info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
       Request starting HTTP/2.0 POST http://localhost/wallet application/json 
 [2019-03-13 13:27:18Z] info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
       Request finished in 52.0584ms 200

**Comment by loning** [comment]
https://travis-ci.org/AElfProject/AElf/builds/505756495?utm_source=github_status&utm_medium=notification

**Comment by rosona** [comment]
Fixed
