### ISSUE TITLE
[FN]Exception while run full node: ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: delay

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#1337]
Run 5bps and 5 full nodes, the full node while hit the ERROR: Elf.Kernel.Miner.Application.BlockMiningEventHandler - System.NullReferenceException: Object reference not set to an instance of an object.

```
ERROR AElf.Kernel.Miner.Application.BlockMiningEventHandler - System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Consensus.Application.ConsensusService.GenerateConsensusTransactionsAsync() in /home/zhengyue/github/AElf/AElf.Kernel.Consensus/Application/ConsensusService.cs:line 132
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
   at AElf.Kernel.Consensus.Application.ConsensusTransactionGenerator.GenerateTransactions(Address from, Int64 preBlockHeight, Hash previousBlockHash, List`1& generatedTransactions) in /home/zhengyue/github/AElf/AElf.Kernel.Consensus/Application/ConsensusTransactionGenerator.cs:line 21
   at AElf.Kernel.Miner.Application.SystemTransactionGenerationService.GenerateSystemTransactions(Address from, Int64 preBlockHeight, Hash preBlockHash) in /home/zhengyue/github/AElf/AElf.Kernel.Core/Miner/Application/SystemTransactionGenerationService.cs:line 18
   at AElf.Kernel.Services.MinerService.GenerateSystemTransactions(Hash previousBlockHash, Int64 previousBlockHeight) in /home/zhengyue/github/AElf/AElf.Kernel/Services/MinerService.cs:line 108
   at AElf.Kernel.Services.MinerService.MineAsync(Hash previousBlockHash, Int64 previousBlockHeight, DateTime time) in /home/zhengyue/github/AElf/AElf.Kernel/Services/MinerService.cs:line 63
   at AElf.Kernel.Miner.Application.BlockMiningEventHandler.HandleEventAsync(BlockMiningEventData eventData) in /home/zhengyue/github/AElf/AElf.Kernel/Services/BlockMiningEventHandler.cs:line 27
```

**Comment by YueZh127** [comment]
Update the Error, in the recent dev version, the full node will get the ERROR:
```
2019-03-27 10:56:59,332 [44] ERROR AElf.Kernel.Miner.Application.BlockMiningEventHandler - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: delay
   at System.Threading.CancellationTokenSource.CancelAfter(TimeSpan delay)
   at AElf.Kernel.Services.MinerService.MineAsync(Hash previousBlockHash, Int64 previousBlockHeight, DateTime time) in /home/zhengyue/github/AElf/AElf.Kernel/Services/MinerService.cs:line 80
   at AElf.Kernel.Miner.Application.BlockMiningEventHandler.HandleEventAsync(BlockMiningEventData eventData) in /home/zhengyue/github/AElf/AElf.Kernel/Services/BlockMiningEventHandler.cs:line 27  
```

**Comment by YueZh127** [comment]
Verify on the latest dev, and this issue didn't recur
