### ISSUE TITLE
Error while sending block AElf.OS.Network.Application.NetworkService 

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#1339]
Run 5bps and 5 full nodes, sometimes bp node or full node will hit the ERROR while sending block.

```
ERROR AElf.OS.Network.Application.NetworkService - Error while sending block.
AElf.OS.Network.Application.NetworkException: Call to peer failed ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Connection reset by peer")
   at AElf.OS.Network.Grpc.GrpcPeer.RequestAsync[TResp](PeerServiceClient client, Func`2 func) in /home/zhengyue/github/AElf/AElf.OS.Network.Grpc/GrpcPeer.cs:line 79
   --- End of inner exception stack trace ---
   at AElf.OS.Network.Grpc.GrpcPeer.HandleFailure(RpcException rpcException) in /home/zhengyue/github/AElf/AElf.OS.Network.Grpc/GrpcPeer.cs:line 120
   at AElf.OS.Network.Grpc.GrpcPeer.RequestAsync[TResp](PeerServiceClient client, Func`2 func) in /home/zhengyue/github/AElf/AElf.OS.Network.Grpc/GrpcPeer.cs:line 83
   at AElf.OS.Network.Grpc.GrpcPeer.AnnounceAsync(PeerNewBlockAnnouncement header) in /home/zhengyue/github/AElf/AElf.OS.Network.Grpc/GrpcPeer.cs:line 66
   at AElf.OS.Network.Application.NetworkService.BroadcastAnnounceAsync(BlockHeader blockHeader) in /home/zhengyue/github/AElf/AElf.OS.Core/Network/Application/NetworkService.cs:line 48
```

**Comment by samfrb** [comment]
It seems the exceptions are normal, cause by the restart of the node.

**Comment by YueZh127** [comment]
Close the issue
