### ISSUE TITLE
AElf.Sdk.CSharp.AssertionException: Incorrect round number for next round.

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#1353]
Run 5bps for a while, and some bps will hit this Error.

```
2019-03-22 06:31:01,799 [21] INFO  AElf.Kernel.SmartContractExecution.Application.FullBlockchainExecutingService - Executed block "cf40ce26f935daef88aa355afe9b96dcb221b96081056b1b0127f0632200f3b2" at height 53.
2019-03-22 06:31:01,818 [21] ERROR AElf.Kernel.SmartContract.Application.TransactionExecutingService - 
AElf.Sdk.CSharp.AssertionException: Incorrect round number for next round.
   at AElf.Sdk.CSharp.CSharpSmartContractAbstract.Assert(Boolean asserted, String message)
   at AElf.Contracts.Consensus.DPoS.ConsensusContract.NextRound(Round input)
   at AElf.Types.CSharp.UnaryServerCallHandler`2.Execute(Byte[] input) in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/ServerCallHandler.cs:line 57
   at AElf.Runtime.CSharp.Executive3.ExecuteMainTransaction() in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/Executive3.cs:line 148
2019-03-22 06:31:01,823 [21] ERROR AElf.Kernel.SmartContract.Application.TransactionExecutingService - 
AElf.Sdk.CSharp.AssertionException: Incorrect round number for next round.
   at AElf.Sdk.CSharp.CSharpSmartContractAbstract.Assert(Boolean asserted, String message)
   at AElf.Contracts.Consensus.DPoS.ConsensusContract.NextRound(Round input)
   at AElf.Types.CSharp.UnaryServerCallHandler`2.Execute(Byte[] input) in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/ServerCallHandler.cs:line 57
   at AElf.Runtime.CSharp.Executive3.ExecuteMainTransaction() in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/Executive3.cs:line 148
2019-03-22 06:31:01,826 [21] INFO  AElf.Kernel.SmartContractExecution.Application.FullBlockchainExecutingService - Executed block "fd06e3a5ba6e0c445b88aa98e1e03ad8dee153e03eb6a903bb65df759f7e5aa4" at height 54.

```

**Comment by EanCuznaivy** [comment]
This error message is due to the round number of input for `NextRound` method is less than or equal to round number of current state.
The only most possible reason is this node received a block from branched chain and tried to execute.
Should be normal if circumstance above meets.
