### ISSUE TITLE
 The node got SocketException during send transaction

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#1433]
Run 5 bp nodes and send a lot of transactions on bp1, sometimes the node got SocketException.

```
2019-03-26 09:06:47,907 [93] INFO  Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets - Connection id "0HLLHNFDQ54CF" communication error.
System.Net.Sockets.SocketException (88): Socket operation on non-socket
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()

```

**Comment by YueZh127** [comment]
Verify on the latest dev, and this issue not occur
