### ISSUE TITLE
Two issue due to key during send transaction

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#1435]
1.  Failed to finish block sync job
```
ERROR Volo.Abp.BackgroundJobs.BackgroundJob - Failed to finish block sync job
System.ArgumentException: An item with the same key has already been added. Key: "b5c3f8f7df1b3198c1bd0839294358228d35cd543af5a1c132538bfdd7d0f16f"
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at AElf.Kernel.TransactionPool.Infrastructure.TxHub.AddToRespectiveCurrentCollection(TransactionReceipt receipt) in /home/zhengyue/github/AElf/AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs:line 169
   at AElf.Kernel.TransactionPool.Infrastructure.TxHub.HandleBestChainFoundAsync(BestChainFoundEventData eventData) in /home/zhengyue/github/AElf/AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs:line 238
   at AElf.Kernel.TransactionPool.Application.TxPoolInterestedEventsHandler.HandleEventAsync(BestChainFoundEventData eventData) in /home/zhengyue/github/AElf/AElf.Kernel.TransactionPool/Application/TxPoolInterestedEventsHandler.cs:line 34
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType, Object eventData, List`1 exceptions)
   at Volo.Abp.EventBus.Local.LocalEventBus.PublishAsync(Type eventType, Object eventData)
   at AElf.Kernel.SmartContractExecution.Application.FullBlockchainExecutingService.ExecuteBlocksAttachedToLongestChain(Chain chain, BlockAttachOperationStatus status) in /home/zhengyue/github/AElf/AElf.Kernel.SmartContractExecution/Application/IBlockExecutingService.cs:line 113
   at AElf.OS.Jobs.BlockSyncJob.AttachBlockToChain(Block block) in /home/zhengyue/github/AElf/AElf.OS/Jobs/BlockSyncJob.cs:line 120
   at AElf.OS.Jobs.BlockSyncJob.ExecuteAsync(BlockSyncJobArgs args) in /home/zhengyue/github/AElf/AElf.OS/Jobs/BlockSyncJob.cs:line 48

```

2. An unhandled exception was thrown by the application.

```
ERROR Microsoft.AspNetCore.Server.Kestrel - Connection id "0HLLHNFDQ6IN1", Request id "0HLLHNFDQ6IN1:00000001": An unhandled exception was thrown by the application.
System.ArgumentException: An item with the same key has already been added. Key: "13062a8f5e83b15022dd48150f51f0b43c9d5862cd2dfbc1a76f73290676b22c"
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at AElf.Kernel.TransactionPool.Infrastructure.TxHub.AddToRespectiveCurrentCollection(TransactionReceipt receipt) in /home/zhengyue/github/AElf/AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs:line 169
   at AElf.Kernel.TransactionPool.Infrastructure.TxHub.HandleTransactionsReceivedAsync(TransactionsReceivedEvent eventData) in /home/zhengyue/github/AElf/AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs:line 209
   at AElf.Kernel.TransactionPool.Application.TxPoolInterestedEventsHandler.HandleEventAsync(TransactionsReceivedEvent eventData) in /home/zhengyue/github/AElf/AElf.Kernel.TransactionPool/Application/TxPoolInterestedEventsHandler.cs:line 24
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType, Object eventData, List`1 exceptions)
   at Volo.Abp.EventBus.Local.LocalEventBus.PublishAsync(Type eventType, Object eventData)
   at AElf.OS.Rpc.ChainController.ServiceExtensions.PublishTransactionsAsync(ChainControllerRpcService s, String[] rawTransactions) in /home/zhengyue/github/AElf/AElf.OS.Rpc.ChainController/ServiceExtensions.cs:line 53
   at AElf.OS.Rpc.ChainController.ChainControllerRpcService.BroadcastTransaction(String rawTransaction) in /home/zhengyue/github/AElf/AElf.OS.Rpc.ChainController/ChainControllerRpcService.cs:line 103
   at CallSite.Target(Closure , CallSite , Object )
   at Anemonis.AspNetCore.JsonRpc.JsonRpcServiceHandler`1.HandleAsync(JsonRpcRequest request)
   at Anemonis.AspNetCore.JsonRpc.JsonRpcMiddleware`1.CreateJsonRpcResponseAsync(HttpContext context, JsonRpcMessageInfo`1 requestInfo)
   at Anemonis.AspNetCore.JsonRpc.JsonRpcMiddleware`1.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by rosona** [comment]
Fixed.
