### ISSUE TITLE
AssertionException: Failed to update term number.

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#1436]
When run 5 bp nods for a while, and all the nodes got `AssertionException: Failed to update term number` 

```
2019-03-26 12:55:59,909 [59] WARN  AElf.Kernel.TransactionPool.Infrastructure.TxHub - Attempting to retrieve executable transactions while best chain records don't macth.
2019-03-26 12:55:59,913 [59] ERROR AElf.Kernel.SmartContract.Application.TransactionExecutingService -
AElf.Sdk.CSharp.AssertionException: Failed to update term number.
   at AElf.Sdk.CSharp.CSharpSmartContractAbstract.Assert(Boolean asserted, String message)
   at AElf.Contracts.Consensus.DPoS.ConsensusContract.NextTerm(Round input)
   at AElf.Types.CSharp.UnaryServerCallHandler`2.Execute(Byte[] input) in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/ServerCallHandler.cs:line 57
   at AElf.Runtime.CSharp.Executive.ExecuteMainTransaction() in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/Executive.cs:line 139
2019-03-26 12:55:59,913 [59] ERROR AElf.Kernel.SmartContract.Application.TransactionExecutingService -
AElf.Sdk.CSharp.AssertionException: Failed to update term number.
   at AElf.Sdk.CSharp.CSharpSmartContractAbstract.Assert(Boolean asserted, String message)
   at AElf.Contracts.Consensus.DPoS.ConsensusContract.NextTerm(Round input)
   at AElf.Types.CSharp.UnaryServerCallHandler`2.Execute(Byte[] input) in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/ServerCallHandler.cs:line 57
   at AElf.Runtime.CSharp.Executive.ExecuteMainTransaction() in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/Executive.cs:line 139
2019-03-26 12:55:59,925 [59] DEBUG AElf.Kernel.SmartContract.Application.SmartContractBridgeService - TX = e0aa194c655e43487badda1314b12353df041088f578ba6a4b61f4289f93c8ac, Method = AddDividends, Dividends of term 49: 1680
```

**Comment by YueZh127** [comment]
Verify on the latest dev, and this issue didn't recur
