### ISSUE TITLE
When the first change miner, the method SendDividends Failed

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#1444]
Run 3bps and 2 full node, the first first change miner, the method SendDividends Failed.

```
2019-03-27 10:22:04,074 [37] TRACE AElf.Kernel.LibBestChainFoundEventHandler - Transaction failed, transactionHash: "923de54cf697fa5003168dc6e78cbc9f498b292e25b57e2642925afa41ec1d4b", error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Contracts.Consensus.DPoS.ConsensusContract.SendDividends(TermInfo input)
   at AElf.Types.CSharp.UnaryServerCallHandler`2.Execute(Byte[] input) in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/ServerCallHandler.cs:line 57
   at AElf.Runtime.CSharp.Executive.ExecuteMainTransaction() in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/Executive.cs:line 134

```
```

{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "TransactionId": "923de54cf697fa5003168dc6e78cbc9f498b292e25b57e2642925afa41ec1d4b",
        "Status": "Failed",
        "Error": "\nSystem.NullReferenceException: Object reference not set to an instance of an object.\n   at AElf.Contracts.Consensus.DPoS.ConsensusContract.SendDividends(TermInfo input)\n   at AElf.Types.CSharp.UnaryServerCallHandler`2.Execute(Byte[] input) in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/ServerCallHandler.cs:line 57\n   at AElf.Runtime.CSharp.Executive.ExecuteMainTransaction() in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/Executive.cs:line 134",
        "Transaction": {
            "From": "46Lp1uYigYVg9g82u1dJhTE2Nex5JP21DF6hD7gtT9nnibN",
            "To": "3sXEJQhEYUXaYgtdX4aePekYeM8yTkgtQ4T1wff2XhawjF6",
            "RefBlockNumber": "173",
            "RefBlockPrefix": "6I3klA==",
            "MethodName": "SendDividends",
            "Params": {
                "termNumber": "2",
                "roundNumber": "51"
            },
            "Sigs": [
                "jmp8RJWo8/1bbDEAcbGViEVi2Qr4zeHnq5/ZuRrAIOJRdcuKpqvb7N+kV7LhvexihP3MlZW3Cm0SM+uWh0QGpwA="
            ]
        }
    }
}
```

**Comment by YueZh127** [comment]
Verify on the latest dev, and this issue didn't recur
