### ISSUE TITLE
Change term since announce election, encountered the error and can't generate block

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#1524]
Run 5bps and ten nodes(including five bps) announce election, after changing term, encountere the error and bp can't generate block.
```
2019-04-10 08:31:52,484 [33] ERROR AElf.Kernel.Miner.Application.BlockMiningEventHandler - AElf.Kernel.SmartContract.Application.SmartContractExecutingException: 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Google.Protobuf.Collections.MapField`2.get_Item(TKey key)
   at AElf.Contracts.Consensus.DPoS.ConsensusContract.ShareAndRecoverInValue(Round round, Round previousRound, Hash inValue, String publicKey)
   at AElf.Contracts.Consensus.DPoS.ConsensusContract.GetInformationToUpdateConsensus(DPoSTriggerInformation input)
   at AElf.Types.CSharp.UnaryServerCallHandler`2.Execute(Byte[] input) in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/ServerCallHandler.cs:line 57
   at AElf.Runtime.CSharp.Executive.Execute() in /home/zhengyue/github/AElf/AElf.Runtime.CSharp/Executive.cs:line 128
   at AElf.Kernel.SmartContract.Application.TransactionReadOnlyExecutionServiceExtensions.ExecuteAsync[T](ITransactionReadOnlyExecutionService transactionReadOnlyExecutionService, IChainContext chainContext, Transaction transaction, DateTime currentBlockTime, Boolean failedThrowException) in /home/zhengyue/github/AElf/AElf.Kernel.SmartContract/Application/ITransactionReadOnlyExecutionService.cs:line 42
   at AElf.Kernel.SmartContract.Application.TransactionReadOnlyExecutionServiceExtensions.ExecuteAsync[T](ITransactionReadOnlyExecutionService transactionReadOnlyExecutionService, IChainContext chainContext, Transaction transaction, DateTime currentBlockTime) in /home/zhengyue/github/AElf/AElf.Kernel.SmartContract/Application/ITransactionReadOnlyExecutionService.cs:line 50
   at AElf.Kernel.Consensus.DPoS.Application.DPoSInformationGenerationService.ExecuteContractAsync[T](IChainContext chainContext, String consensusMethodName, IMessage input, DateTime dateTime) in /home/zhengyue/github/AElf/AElf.Kernel.Consensus.DPoS/Application/DPoSInformationGenerationService.cs:line 122
   at AElf.Kernel.Consensus.DPoS.Application.DPoSInformationGenerationService.GetInformationToUpdateConsensusAsync(ChainContext chainContext, DateTime nextMiningTime) in /home/zhengyue/github/AElf/AElf.Kernel.Consensus.DPoS/Application/DPoSInformationGenerationService.cs:line 128
   at AElf.Kernel.Consensus.Application.ConsensusService.GetInformationToUpdateConsensusAsync(ChainContext chainContext) in /home/zhengyue/github/AElf/AElf.Kernel.Consensus/Application/ConsensusService.cs:line 103
   at AElf.Kernel.Consensus.DPoS.Application.ConsensusExtraDataProvider.GetExtraDataForFillingBlockHeaderAsync(BlockHeader blockHeader) in /home/zhengyue/github/AElf/AElf.Kernel.Consensus.DPoS/Application/ConsensusExtraDataProvider.cs:line 26
   at AElf.Kernel.Blockchain.Application.BlockExtraDataService.FillBlockExtraData(BlockHeader blockHeader) in /home/zhengyue/github/AElf/AElf.Kernel.Core/Blockchain/Application/BlockExtraDataService.cs:line 23
   at AElf.Kernel.Blockchain.Application.BlockGenerationService.GenerateBlockBeforeExecutionAsync(GenerateBlockDto generateBlockDto) in /home/zhengyue/github/AElf/AElf.Kernel.Core/Blockchain/Application/IBlockGenerationService.cs:line 64
   at AElf.Kernel.Services.MiningService.GenerateBlock(Hash preBlockHash, Int64 preBlockHeight, DateTime expectedMiningTime) in /home/zhengyue/github/AElf/AElf.Kernel/Services/MinerService.cs:line 122
   at AElf.Kernel.Services.MiningService.MineAsync(Hash previousBlockHash, Int64 previousBlockHeight, List`1 transactions, DateTime blockTime, TimeSpan timeSpan) in /home/zhengyue/github/AElf/AElf.Kernel/Services/MinerService.cs:line 140
   at AElf.Kernel.Services.MinerService.MineAsync(Hash previousBlockHash, Int64 previousBlockHeight, DateTime dateTime, TimeSpan timeSpan) in /home/zhengyue/github/AElf/AElf.Kernel/Services/MinerService.cs:line 59
   at AElf.Kernel.Miner.Application.BlockMiningEventHandler.HandleEventAsync(ConsensusRequestMiningEventData eventData) in /home/zhengyue/github/AElf/AElf.Kernel/Services/BlockMiningEventHandler.cs:line 34
2019-04-10 08:31:55,940 [19] DEBUG Microsoft.AspNetCore.Server.Kestrel - Connection id "0HLLTHKOM4UI2" started.

```

**Comment by YueZh127** [comment]
Fixed and closed the issue.
