### ISSUE TITLE
Transaction.To is null in GrpcServerTests

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#1643]
**Test case skipped for now. Need to fix later.**

Maybe use mock service instead of real service as injected dependency for `CrossChainGrpcServerBase`.

https://github.com/AElfProject/AElf/blob/9bad3d35c35d74e0b928aa19ce0c266b47080be9/test/AElf.CrossChain.Grpc.Tests/GrpcServerTests.cs#L40

```csharp
Elf.CrossChain.Grpc.GrpcServerTests.RequestIndexingParentChain_WithExtraData

System.InvalidOperationException : Transaction.To cannot be empty: { "From": "Cxh2EpRjieqbDbbQWs6gD16RLNeri6jRm1353nMnDLRrHnxco", "MethodName": "GetIndexedCrossChainBlockDataByHeight" }
   at AElf.Kernel.Transaction.GetSignatureData() in /AElfProject/AElf/src/AElf.Types/Transaction/Transaction.cs:line 26
   at AElf.Kernel.Transaction.GetHash() in /AElfProject/AElf/src/AElf.Types/Transaction/Transaction.cs:line 11
   at AElf.Kernel.SmartContract.Application.TransactionReadOnlyExecutionService.ExecuteAsync(IChainContext chainContext, Transaction transaction, DateTime currentBlockTime) in /AElfProject/AElf/src/AElf.Kernel.SmartContract/Application/ITransactionReadOnlyExecutionService.cs:line 101
   at AElf.CrossChain.CrossChainContractReader.ReadByTransactionAsync[T](Transaction readOnlyTransaction, Hash blockHash, Int64 blockHeight) in /AElfProject/AElf/src/AElf.CrossChain.Core/Helpers/ICrossChainContractReader.cs:line 145
   at AElf.CrossChain.CrossChainContractReader.GetIndexedCrossChainBlockDataAsync(Hash blockHash, Int64 blockHeight) in /AElfProject/AElf/src/AElf.CrossChain.Core/Helpers/ICrossChainContractReader.cs:line 115
   at AElf.CrossChain.CrossChainDataProvider.GetIndexedCrossChainBlockDataAsync(Hash currentBlockHash, Int64 currentBlockHeight) in /AElfProject/AElf/src/AElf.CrossChain.Core/Services/CrossChainDataProvider.cs:line 163
   at AElf.CrossChain.Grpc.CrossChainGrpcServerBase.GetIndexedSideChainBlockInfoResult(Block block) in /AElfProject/AElf/src/AElf.CrossChain.Grpc/Grpc/Server/CrossChainGrpcServerBase.cs:line 80
   at AElf.CrossChain.Grpc.CrossChainGrpcServerBase.CreateParentChainResponse(Block block, Int32 remoteSideChainId) in /AElfProject/AElf/src/AElf.CrossChain.Grpc/Grpc/Server/CrossChainGrpcServerBase.cs:line 144
   at AElf.CrossChain.Grpc.CrossChainGrpcServerBase.WriteResponseStream[T](RequestCrossChainBlockData request, IServerStreamWriter`1 responseStream, Boolean requestSideChain) in /AElfProject/AElf/src/AElf.CrossChain.Grpc/Grpc/Server/CrossChainGrpcServerBase.cs:line 179
   at AElf.CrossChain.Grpc.CrossChainGrpcServerBase.RequestIndexingFromParentChain(RequestCrossChainBlockData request, IServerStreamWriter`1 responseStream, ServerCallContext context) in /AElfProject/AElf/src/AElf.CrossChain.Grpc/Grpc/Server/CrossChainGrpcServerBase.cs:line 41
   at AElf.CrossChain.Grpc.GrpcServerTests.RequestIndexingParentChain_WithExtraData() in /AElfProject/AElf/test/AElf.CrossChain.Grpc.Tests/GrpcServerTests.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by shiwk** [comment]
Fixed in dev brach and close this.
