### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#326]
Running standalone/multinode testing via docker, there would be caught an exception message:
[08:58:12 - Node]: ---- DPoS checking start 

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: data
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields)
   at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)
   at AElf.Kernel.Node.MainChainNode.<>c__DisplayClass64_1.<<DoDPoSMining>b__1>d.MoveNext() in /home/aelf/github/AElf/AElf.Node/Node/MainChainNode.cs:line 753
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

This issue can be reproduced easily at online test environment like(13.115.19.126), repro steps:
1. cd to dir /home/aelf/scripts
2. run script aelf-node.sh, and input nn to start main node
3. input account password to start node, then exception will be popped soon.

**Comment by EanCuznaivy** [comment]
No more such log or possible after latest refactoring of consensus part.

**Comment by EricBlack** [comment]
After retested again, I found trhis issue again, details log in below:
Failed to get dpos info of round 10 System.ArgumentNullException: Value cannot be null.
Parameter name: data
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields)
   at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)
   at AElf.Kernel.Consensus.AElfDPoSHelper.GetRoundInfoToString(UInt64Value roundNumber) in /home/aelf/github/AElf/AElf.Kernel.Consensus/AElfDPoSHelper.cs:line 451
