### ISSUE TITLE
CLI - Exception will be accoured when input part of command and press Tab key before complete command loaded

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#329]
Tested at online machine, due to web speed issue, when we input a part of command and press tab key, then exception happended. Message in below:

aelf> c   
Unhandled Exception: ^[[35;1RSystem.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Internal.ReadLine.KeyHandler.MoveCursorLeft()
   at Internal.ReadLine.KeyHandler.Backspace()
   at Internal.ReadLine.KeyHandler.StartAutoComplete()
   at Internal.ReadLine.KeyHandler.Handle(ConsoleKeyInfo keyInfo)
   at System.ReadLine.GetText(KeyHandler keyHandler)
   at System.ReadLine.Read(String prompt, String default)
   at AElf.CLI.AElfCliProgram.StartRepl() in /home/aelf/github/AElf/AElf.CLI/AElfCliProgram.cs:line 99
   at AElf.CLI.Program.Main(String[] args) in /home/aelf/github/AElf/AElf.CLI/Program.cs:line 59

**Comment by rosona** [comment]
Implemented CLI2, so close this issue about CLI v1
