### ISSUE TITLE
Block synchronzing failed NServiceKit.Redis.RedisResponseException

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#419]
[2018-08-25 01:59:43.804 - Node]: Block synchronzing failed NServiceKit.Redis.RedisResponseException: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error., sPort: 34290, LastCommand:
   at NServiceKit.Redis.RedisNativeClient.CreateResponseError(String error)
   at NServiceKit.Redis.RedisNativeClient.ExpectSuccess()
   at NServiceKit.Redis.RedisClient.Set[T](String key, T value)
   at NServiceKit.Redis.RedisClientManagerCacheClient.Set[T](String key, T value)
   at AElf.Database.RedisDatabase.SetAsync(String key, Byte[] bytes) in /home/aelf/github/AElf/AElf.Database/RedisDatabase.cs:line 26
   at AElf.Kernel.Storages.WorldStateStore.InsertWorldStateAsync(Hash chainId, Hash blockHash, ChangesDict changes) in /home/aelf/github/AElf/AElf.Kernel/Storages/WorldStateStore.cs:line 23
   at AElf.SmartContract.WorldStateDictator.SetWorldStateAsync(Hash preBlockHash) in /home/aelf/github/AElf/AElf.SmartContract/Contexts/WorldStateDictator.cs:line 282
   at AElf.Miner.Miner.BlockExecutor.ExecuteBlock(IBlock block) in /home/aelf/github/AElf/AElf.Miner/Miner/BlockExecutor.cs:line 56
   at AElf.Kernel.Node.MainchainNodeService.ExecuteAndAddBlock(IBlock block) in /home/aelf/github/AElf/AElf.Node/AElfChain/MainchainNodeService.cs:line 360

Note: After long time running, node sync block failed due to redis snapshot error.

**Comment by EricBlack** [comment]
After ignore this issue and set redis config item "set stop-writes-on-bgsave-error" value as no, snapshot would be still failed, node can be still work but block height not correct.

**Comment by rosona** [comment]
Server configuration problem, fix it. Wait a few days to see if it is reproduced.

**Comment by EricBlack** [comment]
Close it due to config issue, not code issue and can be fixed via modify redis configuration.
