### ISSUE TITLE
Failed to get current round number

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#435]
EBP Timeslot of current round: 2018-09-03 07:43:02Z
Current Round : 45. Current height: 90 
[2018-09-03 07:42:53.756 - Node]: Log dpos information - End 
[2018-09-03 07:42:53.756 - P2P]: Broadcasted block "0x7dfab66dd27ec9f6f35d1c991cf0f6ad012573755534e8e4cb89857964fd86b4" to peers with 1 tx(s). Block height: [90]. 
[2018-09-03 07:43:01.741 - Node]: Failed to get current round number. 
[2018-09-03 07:43:01.744 - Node]: Try to insert DPoS transaction to pool: 0x8d12e5a19a26fb32d57f903d3e89d3c8fbc0a4533aced18b91f60da88161827c, threadId: 8 
[2018-09-03 07:43:05.745 - Node]: Failed to get current round number. 
[2018-09-03 07:43:05.745 - Node]: Failed to get DPoS information of current round. System.ArgumentNullException: Value cannot be null.
Parameter name: data
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields)
   at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)
   at AElf.Kernel.Consensus.AElfDPoSHelper.get_CurrentRoundInfo()
[2018-09-03 07:43:05.745 - Node]: Failed to supply previous round info System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Consensus.AElfDPoSHelper.SupplyPreviousRoundInfo()
[2018-09-03 07:43:05.748 - Node]: Failed to get current round number. 
[2018-09-03 07:43:05.748 - Node]: Failed to get BPInfo of current round. System.ArgumentNullException: Value cannot be null.
Parameter name: data
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields)
   at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)
   at AElf.Kernel.Consensus.AElfDPoSHelper.get_Item(String accountAddress)
[2018-09-03 07:43:05.748 - Node]: Failed to generate info of next round System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Consensus.AElfDPoSHelper.GenerateNextRoundOrder()
[2018-09-03 07:43:05.748 - Node]: Failed to get current round number. 
[2018-09-03 07:43:05.748 - Node]: Failed to get first order prodocuer of current round. System.ArgumentNullException: Value cannot be null.
Parameter name: data
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields)
   at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)
   at AElf.Kernel.Consensus.AElfDPoSHelper.get_FirstPlaceBlockProducerOfCurrentRound()
[2018-09-03 07:43:05.748 - Node]: Failed to set next extra block producer System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Consensus.AElfDPoSHelper.CalculateNextExtraBlockProducer()
[2018-09-03 07:43:05.752 - Node]: Try to insert DPoS transaction to pool: 0x7107767af975c934df40512d64217f8dff568a8f479c8f79aacbbc6df10ad9ef, threadId: 3 
[2018-09-03 07:43:05.752 - Node]: AElfDPoSObserver completed. 
[2018-09-03 07:43:05.756 - Node]: Mine - Entered mining 0 
[2018-09-03 07:43:05.756 - Txpool]: Got 2 DPoS tx 
[2018-09-03 07:43:05.756 - Txpool]: Only 0 Contract tx(s) in pool are ready: less than 1. 
[2018-09-03 07:43:05.756 - Miner]: Executing Transactions.. 
[2018-09-03 07:43:05.764 - Miner]: Executed Transactions. 
[2018-09-03 07:43:05.764 - Miner]: Generated block 1. 
[2018-09-03 07:43:05.769 - Miner]: Mining failed with exception. System.InvalidOperationException: Parent is unknown.
   at AElf.Kernel.LightChain.CheckHeaderAppendable(IBlockHeader header)
   at AElf.Kernel.LightChain.AddHeaderAsync(IBlockHeader header)
   at AElf.Kernel.BlockChain.AddBlockAsync(IBlock block)
   at AElf.Kernel.BlockChain.AddBlocksAsync(IEnumerable`1 blocks)
   at AElf.Miner.Miner.Miner.Mine(Int32 timeoutMilliseconds)
[2018-09-03 07:43:05.769 - BlockSync]: Height has been incremented, new value: 92 
[2018-09-03 07:43:05.769 - Node]: Mine - Leaving mining 1 
[2018-09-03 07:43:05.769 - Node]: Somehow failed to update DPoS observables. Will recover soon. System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Node.DPoS.Update()
   at AElf.Kernel.Node.DPoS.Mine()
[2018-09-03 07:43:05.779 - Node]: Block producer number:3 
[2018-09-03 07:43:05.779 - Node]: Start a new round though this behavior doing nothing. 
[2018-09-03 07:43:05.779 - Node]: Will produce normal block after 4s

**Comment by EricBlack** [comment]
Close due to fixed.
