### ISSUE TITLE
Rpc: Huge number of contracts request caused block generate exception

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#472]
1. Without parallel mode:
Steps:
1). Set block volumn with huge number(>10000)
2). Send huge numbers of contract request 
Result:
Node cannot work normally, no new block generated after a while and no error message print out. And the last block number is 0
Log Message:
Broadcasted block "0x696c54904951da757ea1fe2331f098cd579a534c7c9928ece8612eb4e09cadfa" to peers with 0 tx(s). Block height: [17].

2. With Parallel mode:
Steps:
1). Launch lighthouse and few workers.
2). Launch standalone parallel mode with correct parameter.
3). Send huge numbers of contract request
Result:
Node cannot work normally , no new blocks generated after a while. And a lot of warning message in worker log. Message like below:
[2018-09-17 19:07:31.452 - Error - Miner][26]: Mining failed with exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at AElf.Execution.ParallelTransactionExecutingService.ExecuteAsync(List`1 transactions, Hash chainId, CancellationToken token) in /home/aelf-test/github/AElf/AElf.Execution/ParallelTransactionExecutingService.cs:line 55
   at AElf.Miner.Miner.Miner.Mine() in /home/aelf-test/github/AElf/AElf.Miner/Miner/Miner.cs:line 100
System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Node.DPoS.Mine() in /home/aelf-test/github/AElf/AElf.Node/Consensus/DPoS.cs:line 147
[2018-09-17 19:07:35.514 - Trace - NetworkManager][36]: [event] tx added to the pool 0x14125a45adc38382e2910889e9cbb80cf56946441a80cad0221acc737b64d416.
[ERROR][9/17/18 11:07:28 AM][Thread 0009][[akka://AElfSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FAElfSystem%40127.0.0.1%3A4053-1#162604579]] No response from remote. Handshake timed out or transport failure detector triggered.
Cause: Unknown
[WARNING][9/17/18 11:07:29 AM][Thread 0011][[akka://AElfSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FAElfSystem%40127.0.0.1%3A4053-1#258920570]] Association with remote system akka.tcp://AElfSystem@127.0.0.1:4053 has failed; address is now gated for 5000 ms. Reason is: [Akka.Remote.EndpointDisassociatedException: Disassociated
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level, Boolean needToThrow)
   at Akka.Actor.ActorCell.<>c__DisplayClass106_0.<Akka.Actor.IUntypedActorContext.Become>b__0(Object m)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)]

**Comment by EricBlack** [comment]
Now no error message print, but would not generate new block after log print "AELfDPoSObserver completed."
