### ISSUE TITLE
Restart nodes testing: multiple nodes

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#485]
Repro steps:
1. Launch multi nodes(3 nodes) with Launcher.
2. After three nodes generate block normally, stop one of node few minutes.
3. Restart stopped node.

Result:
Stopped node cannot sync up block correctly due to "InvalidReferenceBlock" error. 

Detail message in below:
[2018-09-20 03:58:57.799 - Debug - BlockSync][4]: Initial chain height 62.
[2018-09-20 03:58:57.799 - Trace - BlockSync][4]: Initial sync started.
[2018-09-20 03:58:59.623 - Trace - Peer][8]: Sending authentification : { port: 6830, addr: 0x04e0d68232ee12d67af63a8ee47194446be381492325d4c4516920
e624e7142f4d58bcf44669dbbbe8cd55d9804605f59427394278158bd50efc990fe835e74d6b }
[2018-09-20 03:58:59.633 - Debug - PeerManager][10]: Peer authentified and added : { addr: 127.0.0.1:6820, key: 0x04517b99960f48fbd0d3037ab10eaabc0f
74, bp: True }
[2018-09-20 03:59:01.677 - Debug - NetworkManager][5]: New transaction from 127.0.0.1:6820 not added to the pool: InvalidReferenceBlock
[2018-09-20 03:59:01.693 - Debug - BlockSync][5]: Initial synchronisation has started at target height 146.
[2018-09-20 03:59:02.626 - Trace - SyncService][11]: Adding to pending blocks: 0x4e82c42cf5e441fdaec4c70233fdc313239812ac018ae211d71cba10a556ad9f
[03:59:02 - PendingBlockExtensions]Print - Current PendingBlocks list is empty.
[2018-09-20 03:59:02.631 - Debug - BlockSync][11]: Added block to sync { id : 0x4e82c42cf5e441fdaec4c70233fdc313239812ac018ae211d71cba10a556ad9f, in
dex : 146, tx-count : 2 }
[2018-09-20 03:59:02.631 - Trace - BlockSync][11]: There's 1 pending blocks, with synced : 0, non-synced : 1

**Comment by EricBlack** [comment]
New exception log message got:
Mining failed with exception. System.Exception: Cannot find transaction for hash "0x573398d1bfd80fa2c32
f89e61a80090974218df11f5d032aec57d37ec7d46185".
   at AElf.Kernel.TxHub.GetTransactionHolder(Hash txHash) in /home/aelf/github/AElf/AElf.Kernel.TxHub/TxHub.cs:line 250
   at AElf.Kernel.TxHub.ExecutedTx(Hash txHash) in /home/aelf/github/AElf/AElf.Kernel.TxHub/TxHub.cs:line 172
   at AElf.ChainController.TxMemPoolBM.TxPoolServiceBM.GetReadyTxsAsync(Round currentRoundInfo, Hash blockProducerAddress, Double intervals)
   at AElf.Miner.Miner.Miner.Mine(Round currentRoundInfo) in /home/aelf/github/AElf/AElf.Miner/Miner/Miner.cs:line 75
System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Node.DPoS.Mine() in /home/aelf/github/AElf/AElf.Node/Consensus/DPoS.cs:line 154

**Comment by EanCuznaivy** [comment]
[Relate working in progress issue](https://github.com/AElfProject/AElf/issues/478)

**Comment by EricBlack** [comment]
Recently issue #562 casued this issue still repro.

**Comment by EricBlack** [comment]
Close the issue due to fixed and not repro'd again.
