### ISSUE TITLE
Rollback: Readd net peer after removed few moment got sync block exception

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#493]
Repro Steps:
1. Launch three nodes(A, B, C) and running few minutes.
2. Remove one node(C) all two connected peers(A, B) few minutes. 
3. Readd back those two peers(A, B) to C.

Result:
Node C begin execute rollback logic after readd net peers, but got exception.

Message:
**Node A:**
EBP TimeSlot of current round: 2018-09-25 11:50:30Z
Current Round : 67. Current height: 228 
[2018-09-25 11:50:21.571 - Trace - Node][8]: Log dpos information - End 
[2018-09-25 11:50:21.571 - Debug - BlockSync][8]: Block { id : 0x9d7b9d89a054ea568090cd38d0b9003c516fb244f5cf04d6ef05e8429fec9aa8, index: 228 }  was successfully executed. 
[2018-09-25 11:50:21.575 - Trace - BlockSync][8]: Executed the blocks with the following index(es) : 228 
[2018-09-25 11:50:21.575 - Debug - BlockSync][8]: 2 missing txn for block 208 
[2018-09-25 11:50:21.585 - Debug - BlockSync][8]: Requested the following 2 transactions [0x6b97bef9c6f3b695f9a81abb6a511aa3f8c9fe1cb0cd107be8405179d5886130, 0x556193650b61c8d9822cf3b1761aec528ae2136dc0e515686aa8c84fafdec52e] 
[2018-09-25 11:50:21.604 - Debug - NetworkManager][4]: Matched : [0x6b97bef9c6f3b695f9a81abb6a511aa3f8c9fe1cb0cd107be8405179d5886130, 0x556193650b61c8d9822cf3b1761aec528ae2136dc0e515686aa8c84fafdec52e] 
[2018-09-25 11:50:21.614 - Debug - BlockSync][17]: Handling transaction list message : [0x6b97bef9c6f3b695f9a81abb6a511aa3f8c9fe1cb0cd107be8405179d5886130, 0x556193650b61c8d9822cf3b1761aec528ae2136dc0e515686aa8c84fafdec52e] from 192.168.197.29:6800 
[2018-09-25 11:50:21.623 - Warn - BlockSync][17]: Failed to add the following transaction to the pool (reason: InvalidReferenceBlock): {
  "tx": {
    "TxId": "0x6b97bef9c6f3b695f9a81abb6a511aa3f8c9fe1cb0cd107be8405179d5886130",
    "From": "0x043a4caec49d912621889780328d9b9e3d37",
    "To": "0x75c55e486cc734fb081494cd76891b2ade2d",
    "Method": "PublishInValue",
    "IncrementId": 0,
    "RefBlockNumber": 203,
    "RefBlockPrefix": "0xebc3011e",
    "Type": "DposTransaction"
  }
} 
[2018-09-25 11:50:21.628 - Warn - BlockSync][17]: Failed to add the following transaction to the pool (reason: InvalidReferenceBlock): {
  "tx": {
    "TxId": "0x556193650b61c8d9822cf3b1761aec528ae2136dc0e515686aa8c84fafdec52e",
    "From": "0x043a4caec49d912621889780328d9b9e3d37",
    "To": "0x75c55e486cc734fb081494cd76891b2ade2d",
    "Method": "UpdateAElfDPoS",
    "IncrementId": 0,
    "RefBlockNumber": 203,
    "RefBlockPrefix": "0xebc3011e",
    "Type": "DposTransaction"
  }
} 

**Node C**:
[2018-09-25 11:50:10.349 - Trace - SyncService][12]: Switching chain. 
[2018-09-25 11:50:10.349 - Trace - SyncService][12]: Disposed previous consensus observables list. 
[2018-09-25 11:50:10.349 - Trace - SyncService][12]: Rollback to height: 225 
System.Exception: Cannot insert null value.
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 28
[2018-09-25 11:50:10.401 - Error - BlockSync][12]: Error while dequeuing and processing job. System.AggregateException: One or more errors occurred. (One or more errors occurred. (Cannot insert null value.)) ---> System.AggregateException: One or more errors occurred. (Cannot insert null value.) ---> System.Exception: Cannot insert null value.
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 28
   at AElf.Kernel.Managers.ChainManagerBasic.UpdateCurrentBlockHashAsync(Hash chainId, Hash blockHash) in /home/aelf/github/AElf/AElf.Kernel/Managers/ChainManagerBasic.cs:line 35
   at AElf.Kernel.BlockChain.RollbackToHeight(UInt64 height) in /home/aelf/github/AElf/AElf.Kernel/Chain/BlockChain.cs:line 109
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at AElf.Node.BlockCollection.AddBlockToBranchedChains(PendingBlock pendingBlock) in /home/aelf/github/AElf/AElf.Node/BlockCollection.cs:line 327
   at AElf.Node.Protocol.BlockSynchronizer.AddBlockToSync(Block block, IPeer peer, AElfProtocolMsgType msgType) in /home/aelf/github/AElf/AElf.Node/Protocol/BlockSynchronizer.cs:line 454
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at AElf.Node.Protocol.BlockSynchronizer.DoSync() in /home/aelf/github/AElf/AElf.Node/Protocol/BlockSynchronizer.cs:line 263
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Cannot insert null value.) ---> System.Exception: Cannot insert null value.
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 28
   at AElf.Kernel.Managers.ChainManagerBasic.UpdateCurrentBlockHashAsync(Hash chainId, Hash blockHash) in /home/aelf/github/AElf/AElf.Kernel/Managers/ChainManagerBasic.cs:line 35
   at AElf.Kernel.BlockChain.RollbackToHeight(UInt64 height) in /home/aelf/github/AElf/AElf.Kernel/Chain/BlockChain.cs:line 109
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at AElf.Node.BlockCollection.AddBlockToBranchedChains(PendingBlock pendingBlock) in /home/aelf/github/AElf/AElf.Node/BlockCollection.cs:line 327
   at AElf.Node.Protocol.BlockSynchronizer.AddBlockToSync(Block block, IPeer peer, AElfProtocolMsgType msgType) in /home/aelf/github/AElf/AElf.Node/Protocol/BlockSynchronizer.cs:line 454
---> (Inner Exception #0) System.Exception: Cannot insert null value.
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 28
   at AElf.Kernel.Managers.ChainManagerBasic.UpdateCurrentBlockHashAsync(Hash chainId, Hash blockHash) in /home/aelf/github/AElf/AElf.Kernel/Managers/ChainManagerBasic.cs:line 35
   at AElf.Kernel.BlockChain.RollbackToHeight(UInt64 height) in /home/aelf/github/AElf/AElf.Kernel/Chain/BlockChain.cs:line 109<---
<---

[2018-09-25 11:50:21.478 - Debug - NetworkManager][4]: New transaction from 192.168.197.34:6800 not added to the pool: InvalidReferenceBlock 
[2018-09-25 11:50:21.494 - Trace - SyncService][12]: Adding to pending blocks: 0x9d7b9d89a054ea568090cd38d0b9003c516fb244f5cf04d6ef05e8429fec9aa8 
[2018-09-25 11:50:21.494 - Trace - SyncService][12]: Current PendingBlocks: 
[2018-09-25 11:50:21.494 - Trace - SyncService][12]: 0x37116ba294adde95e822d261d9e3e4404db46250e0408d92ecf4f55d7428dc6e - 226 
[2018-09-25 11:50:21.494 - Trace - SyncService][12]: 0x1c50261ff799636ff7b679f4753e5099d5f1250651e17b9f9e8dfecb8bd3d029 - 227 
[2018-09-25 11:50:21.494 - Debug - BlockSync][12]: Added block to sync { id : 0x9d7b9d89a054ea568090cd38d0b9003c516fb244f5cf04d6ef05e8429fec9aa8, index : 228, tx-count : 2 }  
[2018-09-25 11:50:21.494 - Trace - BlockSync][12]: There's 3 pending blocks, with synced : 0, non-synced : 3 
[2018-09-25 11:50:21.494 - Debug - BlockSync][12]: 1 missing txn for block 226 
[2018-09-25 11:50:21.494 - Debug - BlockSync][12]: Requested the following 1 transactions [0xd17c8090fc3a8b46a5dfaf16fcfd29711dd486a05a37d1bffc0f4a1075b96311] 
[2018-09-25 11:50:21.500 - Debug - NetworkManager][4]: Matched : [0xd17c8090fc3a8b46a5dfaf16fcfd29711dd486a05a37d1bffc0f4a1075b96311] 
[2018-09-25 11:50:21.500 - Debug - BlockSync][11]: Handling transaction list message : [0xd17c8090fc3a8b46a5dfaf16fcfd29711dd486a05a37d1bffc0f4a1075b96311] from 192.168.197.34:6800 
[2018-09-25 11:50:21.513 - Warn - BlockSync][11]: Failed to add the following transaction to the pool (reason: InvalidReferenceBlock): {
  "tx": {
    "TxId": "0xd17c8090fc3a8b46a5dfaf16fcfd29711dd486a05a37d1bffc0f4a1075b96311",
    "From": "0x044925cc8f897de915f28692882700e63c78",
    "To": "0x75c55e486cc734fb081494cd76891b2ade2d",
    "Method": "PublishOutValueAndSignature",
    "IncrementId": 0,
    "RefBlockNumber": 221,
    "RefBlockPrefix": "0x2adaffab",
    "Type": "DposTransaction"
  }
}

**Comment by EricBlack** [comment]
Not repro after verified on latest build.
