### ISSUE TITLE
UserScenario: FullNode sync up BP node failed

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#526]
## Description
FullNode sync up BP node failed on standalone node and multiple nodes due to following reasons.
1. Standalone node - InvalidReferenceBlock
```
[2018-10-11 09:02:25.903 - Debug - NetworkManager][4]: New transaction from 192.168.199.222:6800 not added to the pool: InvalidReferenceBlock 
```

2. Multiple nodes - Known Tx
```
[2018-10-11 09:09:56.051 - Warn - BlockSync][13]: Failed to add the following transaction to the pool (reason: KnownTx): {
  "tx": {
    "TxId": "0x99d9c2e762fe713ce37fda984857e42e7e564b9cbd6f0419ceffaf0a654d0379",
    "From": "0x3a03a3b371b78a3fd69eb7a48e1aab1f32a6",
    "To": "0x0183fe382aad3426bb3c9f38efdb506f62b5",
    "Method": "DeploySmartContract",
    "IncrementId": 0,
    "RefBlockNumber": 498,
    "RefBlockPrefix": "0xb2382767",
    "Type": "ContractTransaction"
  }
}
```
## Repro Steps:
1. Launch Standalone BP node or Multiple BP nodes, and use automation testing program to send contract to one BP.
2. Launch FullNode with bootnodes parameter set.

**Comment by EricBlack** [comment]
New error information throw:
```
EBP TimeSlot of current round: 2018-10-18 11:58:05Z
Current Round : 328. Current height: 1309 
[2018-10-18 12:02:29.316 - Trace - AElfDPoSHelper][15]: Log dpos information - End 
[2018-10-18 12:02:29.316 - Trace - BlockSyncService][15]: Will get block of height 1310 from block set to execute. 
[2018-10-18 12:02:29.409 - Trace - BlockSyncService][8]: Block 0xed9368c5c5e8227fbc37fd8d5a5d77c03cd2e4a462b70f35f6f4c26afad826a1 is an invalid block. 
[2018-10-18 12:02:29.409 - Trace - BlockSet][8]: Added block 0xed9368c5c5e8227fbc37fd8d5a5d77c03cd2e4a462b70f35f6f4c26afad826a1 to BlockSet. 
[2018-10-18 12:02:29.409 - Trace - BlockSyncService][8]: Will get block of height 1310 from block set to execute. 
[2018-10-18 12:02:29.472 - Trace - BlockSyncService][15]: Block 0xeaf0cbedccb376811f3a6da82285fd4c7b8ac8212d69271a8701c5c8a1b85aec is a valid block. 
[2018-10-18 12:02:29.472 - Trace - BlockSet][15]: Added block 0xeaf0cbedccb376811f3a6da82285fd4c7b8ac8212d69271a8701c5c8a1b85aec to BlockSet. 
[2018-10-18 12:02:29.472 - Trace - BlockExecutionService][15]: Executing block "0xeaf0cbedccb376811f3a6da82285fd4c7b8ac8212d69271a8701c5c8a1b85aec" 
[2018-10-18 12:02:29.537 - Trace - BlockSyncService][8]: Block 0xeaf0cbedccb376811f3a6da82285fd4c7b8ac8212d69271a8701c5c8a1b85aec is a valid block. 
[2018-10-18 12:02:29.537 - Trace - BlockSet][8]: Added block 0xeaf0cbedccb376811f3a6da82285fd4c7b8ac8212d69271a8701c5c8a1b85aec to BlockSet. 
[2018-10-18 12:02:29.537 - Trace - BlockExecutionService][8]: Executing block "0xeaf0cbedccb376811f3a6da82285fd4c7b8ac8212d69271a8701c5c8a1b85aec" 
[2018-10-18 12:02:29.660 - Debug - StateDictator][15]: Pipeline set 23 data item 
Google.Protobuf.CodedOutputStream+OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.
   at Google.Protobuf.CodedOutputStream.RefreshBuffer()
   at Google.Protobuf.CodedOutputStream.WriteRawByte(Byte value)
   at Google.Protobuf.Collections.RepeatedField`1.WriteTo(CodedOutputStream output, FieldCodec`1 codec)
   at AElf.Kernel.WorldState.WriteTo(CodedOutputStream output) in /home/aelf/github/AElf/AElf.Kernel.Types/Protobuf/Generated/Kernel.g.cs:line 4761
   at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 38
[2018-10-18 12:02:29.715 - Error - BlockExecutionService][16]: ExecuteBlock - Execution failed with exception Google.Protobuf.CodedOutputStream+OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.
   at Google.Protobuf.CodedOutputStream.RefreshBuffer()
   at Google.Protobuf.CodedOutputStream.WriteRawByte(Byte value)
   at Google.Protobuf.Collections.RepeatedField`1.WriteTo(CodedOutputStream output, FieldCodec`1 codec)
   at AElf.Kernel.WorldState.WriteTo(CodedOutputStream output) in /home/aelf/github/AElf/AElf.Kernel.Types/Protobuf/Generated/Kernel.g.cs:line 4761
   at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 38
   at AElf.SmartContract.StateDictator.SetWorldStateAsync() in /home/aelf/github/AElf/AElf.SmartContract/Contexts/StateDictator.cs:line 80
   at AElf.ChainController.BlockExecutionService.UpdateState(IBlock block) in /home/aelf/github/AElf/AElf.ChainController/BlockExecution/BlockExecutionService.cs:line 228
   at AElf.ChainController.BlockExecutionService.ExecuteBlock(IBlock block) in /home/aelf/github/AElf/AElf.ChainController/BlockExecution/BlockExecutionService.cs:line 78 Google.Protobuf.CodedOutputStream+OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.
   at Google.Protobuf.CodedOutputStream.RefreshBuffer()
   at Google.Protobuf.CodedOutputStream.WriteRawByte(Byte value)
   at Google.Protobuf.Collections.RepeatedField`1.WriteTo(CodedOutputStream output, FieldCodec`1 codec)
   at AElf.Kernel.WorldState.WriteTo(CodedOutputStream output) in /home/aelf/github/AElf/AElf.Kernel.Types/Protobuf/Generated/Kernel.g.cs:line 4761
   at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 38
   at AElf.SmartContract.StateDictator.SetWorldStateAsync() in /home/aelf/github/AElf/AElf.SmartContract/Contexts/StateDictator.cs:line 80
   at AElf.ChainController.BlockExecutionService.UpdateState(IBlock block) in /home/aelf/github/AElf/AElf.ChainController/BlockExecution/BlockExecutionService.cs:line 228
   at AElf.ChainController.BlockExecutionService.ExecuteBlock(IBlock block) in /home/aelf/github/AElf/AElf.ChainController/BlockExecution/BlockExecutionService.cs:line 78
[2018-10-18 12:02:29.721 - Debug - StateDictator][8]: Pipeline set 23 data item 
[2018-10-18 12:02:29.733 - Debug - BlockExecutionService][15]: ExecuteBlock - Incorrect merkle trees. 

Unhandled Exception: System.Exception: Cannot find transaction for hash "0x2522c7e08b696816a9e26dcce45cd63446cd4edd7d035bd09d46b642da84dd06".
   at AElf.Kernel.TxHub.GetTransactionHolder(Hash txHash) in /home/aelf/github/AElf/AElf.Kernel.TxHub/TxHub.cs:line 319
   at AElf.Kernel.TxHub.RevertExecutingTx(Hash txHash) in /home/aelf/github/AElf/AElf.Kernel.TxHub/TxHub.cs:line 193
   at AElf.ChainController.TxMemPoolBM.TxPoolServiceBM.Revert(List`1 txsOut) in /home/aelf/github/AElf/AElf.ChainController/TxMemPoolBM/TxPoolServiceBM.cs:line 177
   at AElf.ChainController.BlockExecutionService.Rollback(List`1 readyTxs) in /home/aelf/github/AElf/AElf.ChainController/BlockExecution/BlockExecutionService.cs:line 189
   at AElf.ChainController.BlockExecutionService.Interrupt(String log, List`1 txs, Exception e) in /home/aelf/github/AElf/AElf.ChainController/BlockExecution/BlockExecutionService.cs:line 176
   at AElf.ChainController.BlockExecutionService.ExecuteBlock(IBlock block) in /home/aelf/github/AElf/AElf.ChainController/BlockExecution/BlockExecutionService.cs:line 98
   at AElf.ChainController.BlockSyncService.HandleValidBlock(BlockAccepted message) in /home/aelf/github/AElf/AElf.ChainController/BlockSynchronization/BlockSyncService.cs:line 102
   at AElf.ChainController.BlockSyncService.ReceiveBlock(IBlock block) in /home/aelf/github/AElf/AElf.ChainController/BlockSynchronization/BlockSyncService.cs:line 80
   at AElf.ChainController.BlockSyncService.<.ctor>b__8_0(SyncUnfinishedBlock inHeight) in /home/aelf/github/AElf/AElf.ChainController/BlockSynchronization/BlockSyncService.cs:line 53
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by EricBlack** [comment]
BlockExecutor Error - Incorrect merkle trees
```
[2018-10-22 11:04:35.524 - Debug - NetworkManager][8]: 192.168.197.34:6800 annouced bd91f678209abcba6858e48b7cb87373d20b95c1a57c84af93a6f3406ab82e92 [1126] (unknown) 
[2018-10-22 11:04:35.524 - Trace - Peer][8]: [192.168.197.34:6800] requested block with id bd91f678209abcba6858e48b7cb87373d20b95c1a57c84af93a6f3406ab82e92. 
[2018-10-22 11:04:35.524 - Trace - Peer][8]: [192.168.197.34:6800] peer height increased : 1126. 
[2018-10-22 11:04:35.524 - Trace - IBlockValidationFilter[]][8]: Received block index:1126 
[2018-10-22 11:04:35.524 - Trace - IBlockValidationFilter[]][8]: Current chain height:700 
[2018-10-22 11:04:35.597 - Trace - BlockSynchronizer][8]: Block bd91f678209abcba6858e48b7cb87373d20b95c1a57c84af93a6f3406ab82e92 at 1126 is an invalid block with validation result Pending. 
[2018-10-22 11:04:35.597 - Trace - BlockSet][8]: Added block bd91f678209abcba6858e48b7cb87373d20b95c1a57c84af93a6f3406ab82e92 to BlockSet. 
[2018-10-22 11:04:35.597 - Trace - BlockSynchronizer][8]: Will get block of height 701 from block set to execute. 
[2018-10-22 11:04:35.665 - Trace - BlockSynchronizer][8]: Block 1d521ff83a05a92486915c9aa95131ed9413e117a7042f6b4097018f71a8259d is a valid block. 
[2018-10-22 11:04:35.665 - Trace - BlockSet][8]: Added block 1d521ff83a05a92486915c9aa95131ed9413e117a7042f6b4097018f71a8259d to BlockSet. 
[2018-10-22 11:04:35.665 - Trace - BlockExecutor][8]: Executing block "1d521ff83a05a92486915c9aa95131ed9413e117a7042f6b4097018f71a8259d" 
[11:04:35 - AElfDPoS]Update - Sync dpos info of round 242 succeed
[2018-10-22 11:04:35.821 - Warn - BlockExecutor][10]: ExecuteBlock - Incorrect merkle trees. 
```

**Comment by EricBlack** [comment]
Close this and create new issue #562.
