### ISSUE TITLE
Parallel Without Cluster:  Execution abnormality

### ISSUE THREAD

**Issue by zhxymh** [AElfProject/AElf#535]
### Description:
Run launcher with parallel and without cluster mode. After send some contracts to execution,The node will throw excepions. 

### Launcher Log
EBP TimeSlot of current round: 2018-10-17 15:38:04Z
Current Round : 11. Current height: 21 
[2018-10-17 15:38:00.034 - Trace - Node][7]: Log dpos information - End 
[2018-10-17 15:38:00.034 - Trace - Node][7]: Mine - Leaving mining 1 
[2018-10-17 15:38:03.546 - Trace - Node][15]: A DPoS tx has been generated: 0x1766298afc5dc93285a74c35ea23b83fd30d9e0e615e0478b6044192d21a9ee0 - PublishInValue from 0x779aff3b93d918f7cfa0b2bed090c5e73fa3 
[2018-10-17 15:38:03.546 - Trace - Node][15]: Try to insert DPoS transaction to pool: 0x1766298afc5dc93285a74c35ea23b83fd30d9e0e615e0478b6044192d21a9ee0, threadId: 15 
[2018-10-17 15:38:07.562 - Trace - Node][11]: A DPoS tx has been generated: 0x6b04898b12fc70eb9f3288a39c539c2b6295e67009e89d86a9fcfbb9e080038c - UpdateAElfDPoS from 0x779aff3b93d918f7cfa0b2bed090c5e73fa3 
[2018-10-17 15:38:07.562 - Trace - Node][11]: Try to insert DPoS transaction to pool: 0x6b04898b12fc70eb9f3288a39c539c2b6295e67009e89d86a9fcfbb9e080038c, threadId: 11 
[2018-10-17 15:38:07.566 - Trace - Node][11]: Mine - Entered mining 0 
[2018-10-17 15:38:07.566 - Trace - TxValidator][11]: Txs list: 
[2018-10-17 15:38:07.566 - Trace - TxValidator][11]: 0x6b04898b12fc70eb9f3288a39c539c2b6295e67009e89d86a9fcfbb9e080038c - UpdateAElfDPoS 
[2018-10-17 15:38:07.566 - Trace - TxValidator][11]: 0x1766298afc5dc93285a74c35ea23b83fd30d9e0e615e0478b6044192d21a9ee0 - PublishInValue 
[2018-10-17 15:38:07.566 - Debug - TxPoolServiceBM][11]: Got 2 System tx 
[2018-10-17 15:38:07.566 - Debug - TxPoolServiceBM][11]: Got 502 total tx 
[2018-10-17 15:38:07.566 - Trace - Miner][11]: Will package 2 DPoS txs. 
[2018-10-17 15:38:07.566 - Trace - Miner][11]: 0x6b04898b12fc70eb9f3288a39c539c2b6295e67009e89d86a9fcfbb9e080038c - UpdateAElfDPoS from 0x779aff3b93d918f7cfa0b2bed090c5e73fa3 
[2018-10-17 15:38:07.566 - Trace - Miner][11]: 0x1766298afc5dc93285a74c35ea23b83fd30d9e0e615e0478b6044192d21a9ee0 - PublishInValue from 0x779aff3b93d918f7cfa0b2bed090c5e73fa3 
[2018-10-17 15:38:07.566 - Debug - Miner][11]: Executing Transactions.. 
[2018-10-17 15:38:07.571 - Info - Grouper][11]: Grouper on chainId "0xe763b299cb1ee12b561e2e53ba080e22929a463655b2e3c3e6ff80182a8acf2c" group [502] transactions into [6] groups with sizes [2, 100, 100, 100, 100, 100], There are also 0 transactions failed retriving resource 
[2018-10-17 15:38:07.571 - Info - Grouper][11]: Grouper on chainId ["0xe763b299cb1ee12b561e2e53ba080e22929a463655b2e3c3e6ff80182a8acf2c"] merge 6 groups into 4 groups with sizes [200, 100, 100, 102] 
[2018-10-17 15:38:07.571 - Trace - Node][11]: AElfDPoSObserver completed. 
[2018-10-17 15:38:08.114 - Debug - StateDictator][22]: Pipeline set 51 data item 
[2018-10-17 15:38:08.134 - Debug - StateDictator][18]: Pipeline set 51 data item 
[15:38:08 - AElfDPoS]Update - Sync dpos info of round 12 succeed
[2018-10-17 15:38:08.206 - Debug - StateDictator][27]: Pipeline set 53 data item 
[2018-10-17 15:38:09.095 - Debug - StateDictator][11]: Pipeline set 102 data item 
[2018-10-17 15:38:09.098 - Debug - Miner][11]: Executed Transactions. 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Google.Protobuf.FieldCodec.<>c__16`1.<ForMessage>b__16_2(T message)
   at Google.Protobuf.Collections.RepeatedField`1.CalculateSize(FieldCodec`1 codec)
   at AElf.Kernel.WorldState.CalculateSize() in /home/aelf-test/github/AElf/AElf.Kernel.Types/Protobuf/Generated/Kernel.g.cs:line 4679
   at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf-test/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 38
[2018-10-17 15:38:09.108 - Error - Miner][11]: Mining failed with exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Google.Protobuf.FieldCodec.<>c__16`1.<ForMessage>b__16_2(T message)
   at Google.Protobuf.Collections.RepeatedField`1.CalculateSize(FieldCodec`1 codec)
   at AElf.Kernel.WorldState.CalculateSize() in /home/aelf-test/github/AElf/AElf.Kernel.Types/Protobuf/Generated/Kernel.g.cs:line 4679
   at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
   at AElf.Kernel.Storages.DataStore.InsertAsync[T](Hash pointerHash, T obj) in /home/aelf-test/github/AElf/AElf.Kernel/Storages/DataStore.cs:line 38
   at AElf.SmartContract.StateDictator.SetWorldStateAsync() in /home/aelf-test/github/AElf/AElf.SmartContract/Contexts/StateDictator.cs:line 84
   at AElf.Miner.Miner.Miner.GenerateBlockAsync(Hash chainId, List`1 results) in /home/aelf-test/github/AElf/AElf.Miner/Miner/Miner.cs:line 365
   at AElf.Miner.Miner.Miner.Mine(Round currentRoundInfo) in /home/aelf-test/github/AElf/AElf.Miner/Miner/Miner.cs:line 115
System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Node.DPoS.Mine() in /home/aelf-test/github/AElf/AElf.Node/Consensus/DPoS.cs:line 158
[2018-10-17 15:38:09.110 - Trace - Node][11]: Mine - Leaving mining 1

**Comment by zhxymh** [comment]
Fixed
