### ISSUE TITLE
SSDB: Huge transaction execution on multiple nodes caused SSDB connection exception

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#547]
## Exception 1
```
System.TimeoutException: Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use.
   at NServiceKit.Redis.PooledRedisClientManager.GetReadOnlyClient()
   at NServiceKit.Redis.RedisClientManagerCacheClient.Get[T](String key)
   at AElf.Database.RedisDatabase.GetAsync(String key) in /home/aelf/github/AElf/AElf.Database/RedisDatabase.cs:line 21
   at AElf.Kernel.Storages.StateStore.GetAsync(StatePath path) in /home/aelf/github/AElf/AElf.Kernel/Storages/StateStore.cs:line 61
System.TimeoutException: Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use.
   at NServiceKit.Redis.PooledRedisClientManager.GetReadOnlyClient()
   at NServiceKit.Redis.RedisClientManagerCacheClient.Get[T](String key)
   at AElf.Database.RedisDatabase.GetAsync(String key) in /home/aelf/github/AElf/AElf.Database/RedisDatabase.cs:line 21
   at AElf.Kernel.Storages.StateStore.GetAsync(StatePath path) in /home/aelf/github/AElf/AElf.Kernel/Storages/StateStore.cs:line 61
System.TimeoutException: Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use.
   at NServiceKit.Redis.PooledRedisClientManager.GetReadOnlyClient()
   at NServiceKit.Redis.RedisClientManagerCacheClient.Get[T](String key)
   at AElf.Database.RedisDatabase.GetAsync(String key) in /home/aelf/github/AElf/AElf.Database/RedisDatabase.cs:line 21
   at AElf.Kernel.Storages.StateStore.GetAsync(StatePath path) in /home/aelf/github/AElf/AElf.Kernel/Storages/StateStore.cs:line 61
System.TimeoutException: Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use.
   at NServiceKit.Redis.PooledRedisClientManager.GetReadOnlyClient()
   at NServiceKit.Redis.RedisClientManagerCacheClient.Get[T](String key)
   at AElf.Database.RedisDatabase.GetAsync(String key) in /home/aelf/github/AElf/AElf.Database/RedisDatabase.cs:line 21
   at AElf.Kernel.Storages.StateStore.GetAsync(StatePath path) in /home/aelf/github/AElf/AElf.Kernel/Storages/StateStore.cs:line 61
```

**Comment by rosona** [comment]
Server configuration problem, fix it. Wait a few days to see if it is reproduced.

**Comment by rosona** [comment]
follow this config ssdb: http://ssdb.io/docs/config.html
follow this script config server: https://gist.github.com/luckydev/b2a6ebe793aeacf50ff15331fb3b519d

**Comment by EricBlack** [comment]
After change configuration, the issue not reproduced and close the issue.
