### ISSUE TITLE
Miner: The CancellationTokenSource has been disposed.

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#581]
## Description
BP node stopped due to System.ObjectDisposedException durning lot of transaction execution. Detail error message in below:
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at AElf.Miner.Miner.Miner.<>c__DisplayClass21_0.<Mine>b__0(Object s) in /home/aelf/github/AElf/AElf.Miner/Miner/Miner.cs:line 83
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by EricBlack** [comment]
Change Issue priority from P2 to P3 due to not easy to reproduced.
