### ISSUE TITLE
System.Threading.ReaderWriterLock+ReaderWriterLockApplicationException

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#649]
EBP TimeSlot of current round: 2018-11-28 15:53:58Z
Current Round : 1096. Current height: 4351
[2018-11-28 15:53:53.614 - Trace - AElfDPoSHelper][29]: Log dpos information - End
[2018-11-28 15:53:53.614 - Trace - DPoS][29]: Disposed previous consensus observables list. Will update DPoS information.
[2018-11-28 15:53:53.620 - Trace - AElfDPoSObserver][29]: Will publish in value after 4 seconds
[2018-11-28 15:53:53.620 - Trace - AElfDPoSObserver][29]: Will help to produce extra block after 17 seconds
[2018-11-28 15:53:54.476 - Trace - BlockSet][29]: Removed block ee5b756cb0b1ed4cb2d6750e29f6e54aca45c7ebfe9b753867ecb165cb435a7c from block cache.
[2018-11-28 15:53:54.476 - Trace - AElfDPoSObserver][51]: DPoS NOP.
[2018-11-28 15:53:54.480 - Trace - BlockSet][29]: Added block ee5b756cb0b1ed4cb2d6750e29f6e54aca45c7ebfe9b753867ecb165cb435a7c to executed block dict.
[2018-11-28 15:53:54.599 - Trace - BlockSet][29]: Removed block of height 4286 from executed block dict.
[2018-11-28 15:53:54.609 - Info - Miner][29]: Generate block ee5b756cb0b1ed4cb2d6750e29f6e54aca45c7ebfe9b753867ecb165cb435a7c at height 4351 with 389 txs, duration 11790 ms.
[2018-11-28 15:53:54.636 - Trace - AElfDPoSObserver][42]: DPoS NOP.
[2018-11-28 15:53:54.662 - Trace - FSM][29]: [StateEvent] MiningEnd
[2018-11-28 15:53:54.668 - Trace - NodeStateFSM][29]: [NodeState] Leaving State ProducingBlock
[2018-11-28 15:53:54.672 - Trace - NodeStateFSM][29]: [NodeState] Entering State Caught
[2018-11-28 15:53:54.672 - Trace - DPoS][29]: Lock number increment: 1
[2018-11-28 15:53:54.679 - Trace - NetworkManager][29]: Block accepted, announcing c11de2f9696d1f185d248726383c2f5fe14cb6c62fd3bd2aabed62963c5dc535 to peers (192.168.197.34:6800|192.168.197.13:6800), block height 4352.
[2018-11-28 15:53:54.683 - Warn - NetworkManager][29]: Unexpected situation, executed a block but no peer is currently syncing.
[2018-11-28 15:53:54.683 - Debug - NetworkManager][29]: Catched up all peers.
[2018-11-28 15:53:54.692 - Trace - BlockSynchronizer][29]: BlockHeader validation result: Success - c11de2f9696d1f185d248726383c2f5fe14cb6c62fd3bd2aabed62963c5dc535. Height: *4352*
[2018-11-28 15:53:54.692 - Trace - FSM][29]: [StateEvent] ValidBlockHeader
[2018-11-28 15:53:54.692 - Trace - NodeStateFSM][29]: [NodeState] Leaving State Caught
[2018-11-28 15:53:54.692 - Trace - DPoS][29]: Lock number decrement: 0
[2018-11-28 15:53:54.692 - Trace - NodeStateFSM][29]: [NodeState] Entering State BlockValidating
[2018-11-28 15:53:54.692 - Trace - DPoS][29]: Lock number increment: 1
[2018-11-28 15:53:55.572 - Trace - FSM][29]: [StateEvent] ValidBlock
[2018-11-28 15:53:55.576 - Trace - NodeStateFSM][29]: [NodeState] Leaving State BlockValidating
[2018-11-28 15:53:55.581 - Trace - DPoS][29]: Lock number decrement: 0
[2018-11-28 15:53:55.583 - Trace - NodeStateFSM][29]: [NodeState] Entering State BlockExecuting
[2018-11-28 15:53:55.588 - Trace - DPoS][29]: Lock number increment: 1
[2018-11-28 15:53:55.588 - Info - BlockSynchronizer][29]: Valid block c11de2f9696d1f185d248726383c2f5fe14cb6c62fd3bd2aabed62963c5dc535. Height: *4352*
[2018-11-28 15:53:55.810 - Trace - DPoS][29]: Mine - Leaving DPoS Mining Process - MiningWithUpdatingAElfDPoSInformation.
[2018-11-28 15:54:00.277 - Trace - DPoS][42]: Trying to enter DPoS Mining Process - PublishInValue.
[2018-11-28 15:54:02.751 - Trace - FSM][19]: [StateEvent] StateUpdated
[2018-11-28 15:54:03.028 - Trace - NodeStateFSM][19]: [NodeState] Leaving State BlockExecuting
[2018-11-28 15:54:03.033 - Trace - DPoS][19]: Lock number decrement: 0
[2018-11-28 15:54:03.033 - Trace - NodeStateFSM][19]: [NodeState] Entering State BlockAppending
[2018-11-28 15:54:03.035 - Trace - DPoS][19]: Lock number increment: 1
[2018-11-28 15:54:03.039 - Trace - BlockExecutor][19]: AppendingBlock c11de2f9696d1f185d248726383c2f5fe14cb6c62fd3bd2aabed62963c5dc535
[2018-11-28 15:54:03.039 - Trace - TxRefBlockValidator][19]: Adding Canonical Hash c11de2f9696d1f185d248726383c2f5fe14cb6c62fd3bd2aabed62963c5dc535 of height 4352
[2018-11-28 15:54:03.039 - Trace - TxRefBlockValidator][19]: Removing Canonical Hash of height 4287.
[2018-11-28 15:54:03.369 - Debug - NetworkManager][20]: Peer 192.168.197.13:6800 annouced block 65b85657e8467dd6bb743a9971f65f97a65ab8b56ea20dd36adb1c822b5b3bea height 4353 (unknown)
[2018-11-28 15:54:03.381 - Trace - Peer][5]: [192.168.197.13:6800] Block request sent { hash: 65b85657e8467dd6bb743a9971f65f97a65ab8b56ea20dd36adb1c822b5b3bea }
[2018-11-28 15:54:03.381 - Trace - Peer][20]: [192.168.197.13:6800] height increased: 4353.
[2018-11-28 15:54:03.386 - Trace - MessageReader][50]: Received last packet: 4, total length: 62451.
[2018-11-28 15:54:03.422 - Info - Peer][50]: Receiving block 65b85657e8467dd6bb743a9971f65f97a65ab8b56ea20dd36adb1c822b5b3bea from 192.168.197.13:6800 at height 4353.
[2018-11-28 15:54:03.473 - Trace - BlockSet][20]: Added block 65b85657e8467dd6bb743a9971f65f97a65ab8b56ea20dd36adb1c822b5b3bea to block cache.
[2018-11-28 15:54:03.755 - Trace - NetworkManager][20]: Block accepted, announcing 65b85657e8467dd6bb743a9971f65f97a65ab8b56ea20dd36adb1c822b5b3bea to peers (192.168.197.34:6800|192.168.197.13:6800), block height 4353.
[2018-11-28 15:54:04.020 - Trace - NetworkManager][20]: Catched up to announcements with 192.168.197.13:6800.
[2018-11-28 15:54:04.050 - Debug - NetworkManager][20]: Catched up all peers.
[2018-11-28 15:54:05.839 - Debug - NetworkManager][20]: Peer 192.168.197.13:6800 annouced block 6380c27056b3324a4e30a6939d0ffcc743637992082fb1a81ac1fe051ae51046 height 4354 (unknown)
[2018-11-28 15:54:06.468 - Trace - MessageReader][36]: Received last packet: 2, total length: 31433.
[2018-11-28 15:54:06.473 - Trace - Peer][5]: [192.168.197.13:6800] Block request sent { hash: 6380c27056b3324a4e30a6939d0ffcc743637992082fb1a81ac1fe051ae51046 }
[2018-11-28 15:54:06.468 - Trace - Peer][20]: [192.168.197.13:6800] height increased: 4354.
[2018-11-28 15:54:07.191 - Info - Peer][36]: Receiving block 6380c27056b3324a4e30a6939d0ffcc743637992082fb1a81ac1fe051ae51046 from 192.168.197.13:6800 at height 4354.
[2018-11-28 15:54:09.143 - Trace - BlockSet][20]: Added block 6380c27056b3324a4e30a6939d0ffcc743637992082fb1a81ac1fe051ae51046 to block cache.
[2018-11-28 15:54:11.285 - Info - BlockExecutor][19]: Executed block c11de2f9696d1f185d248726383c2f5fe14cb6c62fd3bd2aabed62963c5dc535 with result Success, 195 txns, duration 13666 ms.
[2018-11-28 15:54:11.313 - Trace - BlockSynchronizer][19]: Execution result of block c11de2f9696d1f185d248726383c2f5fe14cb6c62fd3bd2aabed62963c5dc535: Success. Height *4352*
[2018-11-28 15:54:11.644 - Trace - DPoS][29]: Trying to enter DPoS Mining Process - MiningWithUpdatingAElfDPoSInformation.
[2018-11-28 15:54:11.809 - Trace - NetworkManager][20]: Block accepted, announcing 6380c27056b3324a4e30a6939d0ffcc743637992082fb1a81ac1fe051ae51046 to peers (192.168.197.34:6800|192.168.197.13:6800), block height 4354.
[2018-11-28 15:54:11.821 - Trace - NetworkManager][20]: Catched up to announcements with 192.168.197.13:6800.
[2018-11-28 15:54:11.824 - Debug - NetworkManager][20]: Catched up all peers.
[2018-11-28 15:54:11.839 - Trace - AElfDPoSObserver][29]: AElfDPoSObserver completed.
[2018-11-28 15:54:12.377 - Debug - NetworkManager][20]: Peer 192.168.197.34:6800 annouced block dc3a103e9e4cc3c0ef00fce317ed08e749ab62424c07e0a891c77c545fbb13ba height 4355 (unknown)
[2018-11-28 15:54:12.542 - Trace - Peer][20]: [192.168.197.34:6800] height increased: 4355.
[2018-11-28 15:54:12.544 - Trace - Peer][4]: [192.168.197.34:6800] Block request sent { hash: dc3a103e9e4cc3c0ef00fce317ed08e749ab62424c07e0a891c77c545fbb13ba }
[2018-11-28 15:54:13.004 - Trace - MessageReader][24]: Received last packet: 3, total length: 57880.
[2018-11-28 15:54:13.016 - Info - Peer][24]: Receiving block dc3a103e9e4cc3c0ef00fce317ed08e749ab62424c07e0a891c77c545fbb13ba from 192.168.197.34:6800 at height 4355.
[2018-11-28 15:54:14.325 - Trace - Peer][50]: { "IpAddress": "192.168.197.13", "Port": 6800 } - Current failed count 8.
[2018-11-28 15:54:14.474 - Trace - Peer][50]: { "IpAddress": "192.168.197.13", "Port": 6800 } - 1 pings where dropped [ 7f17b171-8bff-44ee-8387-cab5f09537fc, 4537b4b3-e290-43d2-840a-e097440ec72c ].
[2018-11-28 15:54:15.791 - Trace - Peer][19]: { "IpAddress": "192.168.197.13", "Port": 6800 } - Current failed count 9.
[2018-11-28 15:54:15.793 - Trace - Peer][19]: { "IpAddress": "192.168.197.13", "Port": 6800 } - 1 pings where dropped [ 4537b4b3-e290-43d2-840a-e097440ec72c, 461ba7dc-9dbd-4388-a07b-bd382e1f5e9a ].
[2018-11-28 15:54:16.333 - Trace - BlockSet][20]: Added block dc3a103e9e4cc3c0ef00fce317ed08e749ab62424c07e0a891c77c545fbb13ba to block cache.
[2018-11-28 15:54:16.790 - Trace - NetworkManager][20]: Block accepted, announcing dc3a103e9e4cc3c0ef00fce317ed08e749ab62424c07e0a891c77c545fbb13ba to peers (192.168.197.34:6800|192.168.197.13:6800), block height 4355.
[2018-11-28 15:54:16.790 - Trace - Peer][32]: { "IpAddress": "192.168.197.34", "Port": 6800 } - Current failed count 1.
[2018-11-28 15:54:16.796 - Trace - Peer][43]: { "IpAddress": "192.168.197.13", "Port": 6800 } - Current failed count 10.
[2018-11-28 15:54:17.363 - Trace - Peer][32]: { "IpAddress": "192.168.197.34", "Port": 6800 } - 1 pings where dropped [ 619c76d3-0024-474c-89ed-5a52f5b7d53d ].
[2018-11-28 15:54:17.363 - Trace - Peer][43]: { "IpAddress": "192.168.197.13", "Port": 6800 } - 1 pings where dropped [ 461ba7dc-9dbd-4388-a07b-bd382e1f5e9a, fa994445-c051-4b37-944c-f0b820773c9c, 1e4d1aee-7f7a-4134-97ae-2a29a8b4b9ea ].
[2018-11-28 15:54:17.367 - Trace - Peer][29]: Could not match pong reply 619c76d3-0024-474c-89ed-5a52f5b7d53d.
[2018-11-28 15:54:17.372 - Trace - Peer][50]: Could not match pong reply 4537b4b3-e290-43d2-840a-e097440ec72c.
[2018-11-28 15:54:17.391 - Trace - NetworkManager][20]: Catched up to announcements with 192.168.197.34:6800.
[2018-11-28 15:54:17.391 - Debug - NetworkManager][20]: Catched up all peers.
[2018-11-28 15:54:17.471 - Trace - Peer][50]: Could not match pong reply 461ba7dc-9dbd-4388-a07b-bd382e1f5e9a.

[2018-11-28 15:54:17.612 - Trace - Peer][50]: Could not match pong reply 7f17b171-8bff-44ee-8387-cab5f09537fc.
Unhandled Exception: System.Threading.ReaderWriterLock+ReaderWriterLockApplicationException: The operation has timed out. (Exception from HRESULT: 0x800705B4)
   at System.Threading.ReaderWriterLock.AcquireWriterLock(Int32 millisecondsTimeout)
   at AElf.Synchronization.BlockSynchronization.BlockSet.RemoveExecutedBlock(String blockHashHex) in /home/aelf/github/AElf/AElf.Synchronization/BlockSynchronization/BlockSet.cs:line 125
   at AElf.Synchronization.BlockSynchronization.BlockSet.Tell(IBlock currentExecutedBlock) in /home/aelf/github/AElf/AElf.Synchronization/BlockSynchronization/BlockSet.cs:line 148
   at AElf.Synchronization.BlockSynchronization.BlockSynchronizer.HandleValidBlock(IBlock block) in /home/aelf/github/AElf/AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs:line 285
   at AElf.Synchronization.BlockSynchronization.BlockSynchronizer.HandleBlock(IBlock block) in /home/aelf/github/AElf/AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs:line 254
   at AElf.Synchronization.BlockSynchronization.BlockSynchronizer.ReceiveBlock(IBlock block) in /home/aelf/github/AElf/AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs:line 203
   at AElf.Synchronization.BlockSynchronization.BlockSynchronizer.ReceiveNextValidBlock() in /home/aelf/github/AElf/AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs:line 232
   at AElf.Synchronization.BlockSynchronization.BlockSynchronizer.<.ctor>b__13_1(EnteringState inState) in /home/aelf/github/AElf/AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs:line 79
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by EricBlack** [comment]
Close due to fixed.
