### ISSUE TITLE
RedisResponseException: Zero length respose 

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#679]
Configure with one miner account and launch node will got Error "Zero length respose" and "could not connect redis". Detail message in below:

```
EBP TimeSlot of current round: 2018-12-11 06:38:36Z
Current Round : 355. Current height: 1419 
[2018-12-11 06:38:31.172 - Trace - AElfDPoSHelper][8]: Log dpos information - End 
[2018-12-11 06:38:31.172 - Trace - BlockSet][8]: Removed block 4ae894a1e873f162992646b1a8014b8f5e90e122a4a9b01b8df23bd0ed7033f1 from block cache. 
[2018-12-11 06:38:31.172 - Trace - BlockSet][8]: Added block 4ae894a1e873f162992646b1a8014b8f5e90e122a4a9b01b8df23bd0ed7033f1 to executed block dict. 
[2018-12-11 06:38:31.172 - Trace - BlockSet][8]: Removed block of height 1354 from executed block dict. 
[2018-12-11 06:38:31.172 - Info - Miner][8]: Generate block 4ae894a1e873f162992646b1a8014b8f5e90e122a4a9b01b8df23bd0ed7033f1 at height 1419 with 1 txs, duration 38 ms. 
[2018-12-11 06:38:31.172 - Trace - FSM][8]: [StateEvent] MiningEnd 
[2018-12-11 06:38:31.172 - Trace - NodeStateFSM][8]: [NodeState] Leaving State ProducingBlock 
[2018-12-11 06:38:31.172 - Trace - NodeStateFSM][8]: [NodeState] Entering State Caught 
[2018-12-11 06:38:31.172 - Trace - DPoS][8]: Lock number increment: 1 
[2018-12-11 06:38:31.178 - Trace - DPoS][8]: Mine - Leaving DPoS Mining Process - PublishOutValueAndSignature. 
[2018-12-11 06:38:35.137 - Trace - DPoS][60]: Trying to enter DPoS Mining Process - PublishInValue. 
[2018-12-11 06:38:35.137 - Trace - FSM][60]: [StateEvent] MiningStart 
[2018-12-11 06:38:35.137 - Trace - NodeStateFSM][60]: [NodeState] Leaving State Caught 
[2018-12-11 06:38:35.137 - Trace - DPoS][60]: Lock number decrement: 0 
[2018-12-11 06:38:35.137 - Trace - NodeStateFSM][60]: [NodeState] Entering State GeneratingConsensusTx 
[2018-12-11 06:38:35.137 - Trace - TransactionFilter][60]: Consensus state changed to PublishInValue, will reset dpos tx filter. 
[2018-12-11 06:38:35.137 - Trace - DPoS][60]: Mine - Entered DPoS Mining Process - PublishInValue. 
[2018-12-11 06:38:35.139 - Trace - DPoS][60]: Entered generating tx. 
[2018-12-11 06:38:35.152 - Trace - DPoS][60]: Leaving generating tx. 
[2018-12-11 06:38:35.152 - Trace - FSM][60]: [StateEvent] ConsensusTxGenerated 
[2018-12-11 06:38:35.152 - Trace - NodeStateFSM][60]: [NodeState] Leaving State GeneratingConsensusTx 
[2018-12-11 06:38:35.152 - Trace - NodeStateFSM][60]: [NodeState] Entering State ProducingBlock 
[2018-12-11 06:38:35.152 - Trace - DPoS][60]: A DPoS tx has been generated: 08f67d6c00dd8412a29fea1b8f05d8a114a6fff36e17104b6fc6bc02b50580be - PublishInValue from ELF_29Tivc5bMLr8nXjUvorr5WNLfmjcQdmWVAmXKENxeZyEZic52d. 
[2018-12-11 06:38:35.152 - Trace - DPoS][60]: Try to insert DPoS transaction to pool: 08f67d6c00dd8412a29fea1b8f05d8a114a6fff36e17104b6fc6bc02b50580be threadId: 60 
[2018-12-11 06:38:35.152 - Trace - FSM][60]: [StateEvent] MiningEnd 
[2018-12-11 06:38:35.152 - Trace - NodeStateFSM][60]: [NodeState] Leaving State ProducingBlock 
[2018-12-11 06:38:35.152 - Trace - NodeStateFSM][60]: [NodeState] Entering State Caught 
[2018-12-11 06:38:35.152 - Trace - DPoS][60]: Lock number increment: 1 
[2018-12-11 06:38:35.152 - Trace - DPoS][60]: Mine - Leaving DPoS Mining Process - PublishInValue. 
[2018-12-11 06:38:39.156 - Trace - DPoS][60]: Trying to enter DPoS Mining Process - UpdateAElfDPoS. 
[2018-12-11 06:38:39.156 - Trace - FSM][60]: [StateEvent] MiningStart 
[2018-12-11 06:38:39.156 - Trace - NodeStateFSM][60]: [NodeState] Leaving State Caught 
[2018-12-11 06:38:39.156 - Trace - DPoS][60]: Lock number decrement: 0 
[2018-12-11 06:38:39.156 - Trace - NodeStateFSM][60]: [NodeState] Entering State GeneratingConsensusTx 
[2018-12-11 06:38:39.156 - Trace - TransactionFilter][60]: Consensus state changed to UpdateAElfDPoS, will reset dpos tx filter. 
[2018-12-11 06:38:39.156 - Trace - DPoS][60]: Mine - Entered DPoS Mining Process - UpdateAElfDPoS. 
NServiceKit.Redis.RedisResponseException: Zero length respose, sPort: 48458, LastCommand: 
   at NServiceKit.Redis.RedisNativeClient.CreateResponseError(String error)
   at NServiceKit.Redis.RedisNativeClient.ParseSingleLine(String r)
   at NServiceKit.Redis.RedisClient.Get[T](String key)
   at NServiceKit.Redis.RedisClientManagerCacheClient.Get[T](String key)
   at AElf.Database.RedisDatabase.GetAsync(String database, String key) in /home/zhengyue/github/AElf/AElf.Database/RedisDatabase.cs:line 22
   at AElf.Kernel.Storages.StateStore.GetAsync(StatePath path) in /home/zhengyue/github/AElf/AElf.Kernel/Storages/StateStore.cs:line 63
NServiceKit.Redis.RedisException: could not connect to redis Instance at 127.0.0.1:6379 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 127.0.0.1:6379
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at NServiceKit.Redis.RedisNativeClient.Connect()
   --- End of inner exception stack trace ---
   at NServiceKit.Redis.RedisNativeClient.Connect()
   at NServiceKit.Redis.RedisNativeClient.AssertConnectedSocket()
   at NServiceKit.Redis.RedisNativeClient.SendCommand(Byte[][] cmdWithBinaryArgs)
   at NServiceKit.Redis.RedisNativeClient.SendExpectSuccess(Byte[][] cmdWithBinaryArgs)
   at NServiceKit.Redis.RedisClient.ChangeDb(Int64 db)
   at NServiceKit.Redis.PooledRedisClientManager.GetReadOnlyClient()
   at NServiceKit.Redis.RedisClientManagerCacheClient.Get[T](String key)
   at AElf.Database.RedisDatabase.GetAsync(String database, String key) in /home/zhengyue/github/AElf/AElf.Database/RedisDatabase.cs:line 22
   at AElf.Kernel.Storages.StateStore.GetAsync(StatePath path) in /home/zhengyue/github/AElf/AElf.Kernel/Storages/StateStore.cs:line 63
[2018-12-11 06:38:39.177 - Error - AElfDPoSHelper][60]: Failed to get DPoS information of current round.
 System.AggregateException: One or more errors occurred. (could not connect to redis Instance at 127.0.0.1:6379) ---> NServiceKit.Redis.RedisException: could not connect to redis Instance at 127.0.0.1:6379 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 127.0.0.1:6379
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at NServiceKit.Redis.RedisNativeClient.Connect()
   --- End of inner exception stack trace ---
   at NServiceKit.Redis.RedisNativeClient.Connect()
   at NServiceKit.Redis.RedisNativeClient.AssertConnectedSocket()
   at NServiceKit.Redis.RedisNativeClient.SendCommand(Byte[][] cmdWithBinaryArgs)
   at NServiceKit.Redis.RedisNativeClient.SendExpectSuccess(Byte[][] cmdWithBinaryArgs)
   at NServiceKit.Redis.RedisClient.ChangeDb(Int64 db)
   at NServiceKit.Redis.PooledRedisClientManager.GetReadOnlyClient()
   at NServiceKit.Redis.RedisClientManagerCacheClient.Get[T](String key)
   at AElf.Database.RedisDatabase.GetAsync(String database, String key) in /home/zhengyue/github/AElf/AElf.Database/RedisDatabase.cs:line 22
   at AElf.Kernel.Storages.StateStore.GetAsync(StatePath path) in /home/zhengyue/github/AElf/AElf.Kernel/Storages/StateStore.cs:line 63
   at AElf.SmartContract.DataProvider.GetAsync(String key) in /home/zhengyue/github/AElf/AElf.SmartContract/Contexts/DataProvider.cs:line 97
   at AElf.SmartContract.DataProvider.GetAsync[T](Hash keyHash) in /home/zhengyue/github/AElf/AElf.SmartContract/Contexts/DataProvider.cs:line 159

```

**Comment by rosona** [comment]
Can't reproduce,  it will continue to follow up if happens again.
