### ISSUE TITLE
[CLI2] Run create command got Unhandled Exception

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#692]
Unhandled Exception: Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = JSEngine (ReflectionActivator), Services = [AElf.CLI2.JS.IJSEngine], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(AElf.CLI2.JS.IO.IConsole, AElf.CLI2.Commands.BaseOption, AElf.CLI2.JS.Crypto.IRandomGenerator, ChakraCore.NET.Debug.IDebugAdapter)' on type 'JSEngine'. ---> Unable to load shared library 'ChakraCore.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libChakraCore.dll: cannot open shared object file: No such file or directory (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(AElf.CLI2.JS.IO.IConsole, AElf.CLI2.Commands.BaseOption, AElf.CLI2.JS.Crypto.IRandomGenerator, ChakraCore.NET.Debug.IDebugAdapter)' on type 'JSEngine'. ---> Unable to load shared library 'ChakraCore.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libChakraCore.dll: cannot open shared object file: No such file or directory (See inner exception for details.) ---> System.DllNotFoundException: Unable to load shared library 'ChakraCore.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libChakraCore.dll: cannot open shared object file: No such file or directory
   at ChakraCore.NET.API.Native.JsCreateRuntime(JavaScriptRuntimeAttributes attributes, JavaScriptThreadServiceCallback threadService, JavaScriptRuntime& runtime)
   at ChakraCore.NET.ChakraRuntime.Create(JavaScriptRuntimeAttributes attributes, IServiceNode service, EventWaitHandle syncHandle, UInt64 memoryLimit)
   at ChakraCore.NET.Hosting.JavaScriptHosting.CreateContext(JavaScriptHostingConfig config)
   at AElf.CLI2.JS.JSEngine..ctor(IConsole console, BaseOption option, IRandomGenerator randomGenerator, IDebugAdapter debugAdapter) in /home/aelf/github/AElf/AElf.CLI2/JS/JSEngine.cs:line 76
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at AElf.CLI2.Commands.Command..ctor(BaseOption option) in /home/aelf/github/AElf/AElf.CLI2/Commands/Command.cs:line 22
   at AElf.CLI2.Program.<>c.<Main>b__0_0(CreateOption opt) in /home/aelf/github/AElf/AElf.CLI2/Program.cs:line 24
   at AElf.CLI2.Program.Main(String[] args) in /home/aelf/github/AElf/AElf.CLI2/Program.cs:line 17
Aborted (core dumped)

**Comment by EricBlack** [comment]
publish out to other directory, can repro this issue.
