### ISSUE TITLE
[Proposal] Create multiple sign account issues

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#698]
##Issue List
1. Create account with parameter less than zero, account can be created successfully.
Including:
* executing_threshold
* proposer_threshold
* weight
```
ubuntu@aelf-test-1:/home/aelf/github/AElf/AElf.CLI2/bin/Debug/netcoreapp2.1$ CLI2 create-multi-sig 1 1 '[{"PubKey":"0435e58660a6a04cbf4083b15808568dc4716c2678b2a3f50cb540d4b3381ffa27fa1e4916b2e579c64ca77a92ac40443074a077d99830ba01f95f9f7c6352b436","Weight":"-1"}]' $ENV
Unlocking account ...
Start creating multi sig address..                                                           tx_hash is: 2629f0c061ae2acc15605f9e698bcacec6985a9695045416269a106d617b5a02                 TxStatus is:  Mined                                                                          Multi sig address is:  ELF_NpYc4Xrno4tFsPMMyDhh5ieGu6CAh7Sdg1FZgcDxNDvZQ4
``` 

2. Public Key format not verified.
```
ubuntu@aelf-test-1:/home/aelf/github/AElf/AElf.CLI2/bin/Debug/netcoreapp2.1$ CLI2 create-multi-sig 2 1 '[{"PubKey":"0435e58660a6a04cbf4083b15808568dc471","Weight":"1"}]' $ENV
Unlocking account ...
Start creating multi sig address..                                                           tx_hash is: 43c5fa85871f4e3a7801dcea71780d4b41e4a26883a7a3ae11306f7e5d1bcb41                 TxStatus is:  Mined                                                                          Multi sig address is:  ELF_4VwDWFgTYR9qX4j8DJtG2i82bdBQcw5KWHfEP81HKe1nvjS
```

3. All public key sum of weight less than executing_threshold value not checcked.
```
ubuntu@aelf-test-1:/home/aelf/github/AElf/AElf.CLI2/bin/Debug/netcoreapp2.1$ CLI2 create-multi-sig 2 0 '[{"PubKey":"0435e58660a6a04cbf4083b15808568dc471","Weight":"1"}]' $ENV
Unlocking account ...
Start creating multi sig address..                                                           tx_hash is: 7cd45b5004b48858d14ffe79ac36c0bd592860c8b854be4935a55edb579ef958                 TxStatus is:  Mined                                                                          Multi sig address is:  ELF_4rmhxBbZ93H8H8pjNNFZZCsjA6YRMGFSkCXAEznerBRXDGT
```

4. The max of public key weight should be bigger than proposer_threshold value.
```
ubuntu@aelf-test-1:/home/aelf/github/AElf/AElf.CLI2/bin/Debug/netcoreapp2.1$ CLI2 create-multi-sig 2 2 '[{"PubKey":"0435e58660a6a04cbf4083b15808568dc471","Weight":"1"}]' $ENV
Unlocking account ...
Start creating multi sig address..                                                           tx_hash is: e4c6204ce474919c09c850783f883fcb69535e24b355ba808ab731267fadbfb2                 TxStatus is:  Mined                                                                          Multi sig address is:  ELF_2SRfrFiDun48vHh3tJAeX36ahTyAD5Q35uYHQeLu4dMKFCx
```

5. [CLI2] .Invalid parameter pubkey, return exception
```
ubuntu@aelf-test-1:/home/aelf/github/AElf/AElf.CLI2/bin/Debug/netcoreapp2.1$ CLI2 create-multi-sig 2 0 '[{"Pubkey":"0435e58660a6a04cbf4083b15808568dc4716c2678b2a3f50cb540d4b3381ffa27fa1e4916b2e579c64ca77a92ac40443074a077d99830ba01f95f9f7c6352b436","Weight":"1"},{"Pubkey":"046fc4978a533ea424dcee3db4aa4db06cd4d8c5cec1ad86a152dd9c586c08349da2bf60a8e4d9d01b5ad9f9e36f5477c353acb30086ee41adb5bd79f6b71ed63b","Weight":"1"},{"Pubkey":"04b84eae0b8973f9c11ef22d3430883f6c9f8c14bf590fbe6473cd851c40c739bcc548000ffe6d5c97568904f792714d0f482b98629004e8b79c64e1a49cfbae17","Weight":"1"}]' $ENV
Unlocking account ...
Start creating multi sig address..
Unhandled Exception: ChakraCore.NET.API.JavaScriptScriptException: Script threw an exception. Unable to get property 'replace' of undefined or null reference
   at ChakraCore.NET.API.Native.ThrowIfError(JavaScriptErrorCode error, Boolean ignoreScriptError)
   at ChakraCore.NET.API.JavaScriptValue.CallFunction(JavaScriptValue[] arguments)
   at ChakraCore.NET.JSValueConverterHelper.<>c__DisplayClass39_1`3.<fromJSMethod>b__1()
   at ChakraCore.NET.ContextSwitchService.With(Action a)
   at ChakraCore.NET.JSValueConverterHelper.<>c__DisplayClass39_0`3.<fromJSMethod>b__0(T1 para1, T2 para2, T3 para3)
   at AElf.CLI2.Commands.Proposal.CreateMultiSigAddressCommand.Execute() in /home/aelf/github/AElf/AElf.CLI2/Commands/Proposal/CreateMultiSigAddressCommand.cs:line 37
   at AElf.CLI2.Program.<>c.<Main>b__0_9(CreateMultiSigOption opt) in /home/aelf/github/AElf/AElf.CLI2/Program.cs:line 107
   at AElf.CLI2.Program.Main(String[] args) in /home/aelf/github/AElf/AElf.CLI2/Program.cs:line 17
Aborted (core dumped)
```

**Comment by rosona** [comment]
desgin changed
