### ISSUE TITLE
[Proposal] Create a proposal issue

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#700]
## Issue List
1. Proposal name length not limit.

2. time parameter can be negative value.

3. Msig_address parameter format not verified
```
ubuntu@aelf-test-1:/home/aelf/github/AElf/AElf.CLI2/bin/Debug/netcoreapp2.1$ CLI2 propose "Testing proposal name" ELF_5SLtAu2PfYg7fBzgTHsi3GuX3 100 ELF_4Qna4KWEr9XyxewGNHku1gwUvqtfsARSHcwjd3WXBpLw9Yx Initialize ["aelf","AElf","20000","1"] $ENV
Unlocking account ...

Unhandled Exception: ChakraCore.NET.API.JavaScriptScriptException: Script threw an exception. Invalid checksum
   at ChakraCore.NET.API.Native.ThrowIfError(JavaScriptErrorCode error, Boolean ignoreScriptError)
   at ChakraCore.NET.API.JavaScriptValue.CallFunction(JavaScriptValue[] arguments)
   at ChakraCore.NET.JSValueConverterHelper.<>c__DisplayClass47_1`7.<fromJSMethod>b__1()
   at ChakraCore.NET.ContextSwitchService.With(Action a)
   at ChakraCore.NET.JSValueConverterHelper.<>c__DisplayClass47_0`7.<fromJSMethod>b__0(T1 para1, T2 para2, T3 para3, T4 para4, T5 para5, T6 para6, T7 para7)
   at AElf.CLI2.Commands.Proposal.ProposeCommand.Execute() in /home/aelf/github/AElf/AElf.CLI2/Commands/Proposal/ProposeCommand.cs:line 42
   at AElf.CLI2.Program.<>c.<Main>b__0_10(ProposalOption opt) in /home/aelf/github/AElf/AElf.CLI2/Program.cs:line 116
   at AElf.CLI2.Program.Main(String[] args) in /home/aelf/github/AElf/AElf.CLI2/Program.cs:line 17
Aborted (core dumped)
```

**Comment by rosona** [comment]
design changed
