### ISSUE TITLE
Deploy contract with customer version cause load assembly exception 

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#705]
## Description
If user build contract with version number, then deploy contract to node it will throw load error.

## Contract build command:
```
dotnet publish /p:Version=1.0.123 --configuration Release -o ~/Downloads/aelf
```

## Error Message
```
[2018-12-15 09:13:48.291 - Error - Miner][40]: Mining failed with exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'AElf.Common, Version=1.0.123.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
 ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at AElf.Runtime.CSharp.SmartContractRunner.RunAsync(SmartContractRegistration reg) in /home/ubuntu/workspace/AElfProject/AElf/AElf.Runtime.CSharp/SmartContractRunner.cs:line 75
   at AElf.SmartContract.SmartContractService.GetExecutiveAsync(Address contractAddress, Hash chainId) in /home/ubuntu/workspace/AElfProject/AElf/AElf.SmartContract/SmartContractService.cs:line 90
   at AElf.Execution.Execution.SimpleExecutingService.ExecuteOneAsync(Int32 depth, Transaction transaction, Hash chainId, IChainContext chainContext, Dictionary`2 stateCache, CancellationToken cancellationToken) in /home/ubuntu/workspace/AElfProject/AElf/AElf.Execution/Execution/SimpleExecutingService.cs:line 102
   at AElf.Execution.Execution.SimpleExecutingService.ExecuteAsync(List`1 transactions, Hash chainId, CancellationToken cancellationToken, Hash disambiguationHash, TransactionType transactionType) in /home/ubuntu/workspace/AElfProject/AElf/AElf.Execution/Execution/SimpleExecutingService.cs:line 41
   at AElf.Miner.Miner.Miner.ExecuteTransactions(List`1 txs, Boolean noTimeout, TransactionType transactionType) in /home/ubuntu/workspace/AElfProject/AElf/AElf.Miner/Miner/Miner.cs:line 216
   at AElf.Miner.Miner.Miner.Mine() in /home/ubuntu/workspace/AElfProject/AElf/AElf.Miner/Miner/Miner.cs:line 149
[2018-12-15 09:13:48.295 - Trace - BlockExecutor][40]: Current Event: MiningEnd ,IsLimitExecutionTime: True
```

**Comment by EricBlack** [comment]
Now deploy without issue, but try to execute contract method, node will be stopped working and throw assembly error.

**Comment by rosona** [comment]
Discuss with the team and think that this is an incorrect way to use version, so close it.
