### ISSUE TITLE
Rpc Api 'dpos_isalive' got unhandled exception

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#771]
## Description
2019-01-03 09:08:20,758 [7] ERROR Microsoft.AspNetCore.Server.Kestrel [(null)] - Connection id "0HLJHBC069AI8", Request id "0HLJHBC069AI8:00000001": An unhandled excep
tion was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Node.Consensus.DPoS.IsAlive() in /home/aelf/github/AElf/AElf.Node/Consensus/DPoS.cs:line 780
   at AElf.Node.AElfChain.MainchainNodeService.CheckDPoSAliveAsync() in /home/aelf/github/AElf/AElf.Node/AElfChain/MainchainNodeService.cs:line 176
   at AElf.ChainController.Rpc.ChainControllerRpcService.IsDPoSAlive() in /home/aelf/github/AElf/AElf.ChainController.Rpc/ChainControllerRpcService.cs:line 575
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Community.AspNetCore.JsonRpc.JsonRpcServiceHandler`1.Community.AspNetCore.JsonRpc.IJsonRpcHandler.HandleAsync(JsonRpcRequest request)
   at Community.AspNetCore.JsonRpc.JsonRpcMiddleware`1.CreateJsonRpcResponseAsync(HttpContext context, JsonRpcMessageInfo`1 requestInfo)
   at Community.AspNetCore.JsonRpc.JsonRpcMiddleware`1.Microsoft.AspNetCore.Http.IMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by loning** [comment]
fix in #764
