### ISSUE TITLE
Problem while initialize sync

### ISSUE THREAD

**Issue by zhxymh** [AElfProject/AElf#795]
Three BPs, When the second and third nodes start and initialize sync, both nodes throw exceptions and stop.

Exception:
`
[2019-01-08 19:48:13.234 - Trace - BlockExecutor][5]: Current Event: LongerChainDetected, IsLimitExecutionTime: False. 
[2019-01-08 19:48:13.235 - Trace - FSM][5]: [StateEvent] LongerChainDetected 
[2019-01-08 19:48:13.235 - Trace - NodeStateFSM][5]: [NodeState] Leaving State BlockAppending 
[2019-01-08 19:48:13.235 - Trace - DPoS][5]: Lock number decrement: 0 
[2019-01-08 19:48:13.236 - Warn - BlockSynchronizer][5]: The chain is about to be re-synced from the lib. 
[2019-01-08 19:48:13.245 - Trace - BlockChain][5]: Will rollback to 1 
[2019-01-08 19:48:13.270 - Error - NetworkManager][5]: Error while reset for minority fork. System.InvalidOperationException: Cannot sync genesis height or lower.
   at AElf.Network.Peers.Peer.SyncToHeight(Int32 start, Int32 target) in /Users/zx/Documents/code/AElf/AElf.Network/Peers/Peer.Sync.cs:line 100
   at AElf.Node.Protocol.NetworkManager.OnMinorityForkDetected() in /Users/zx/Documents/code/AElf/AElf.Node/Protocol/NetworkManager.cs:line 415
[2019-01-08 19:48:13.285 - Trace - DPoS][5]: Disposed previous consensus observables list. Will reload new consnesus events. 
[2019-01-08 19:48:13.286 - Trace - BlockExecutor][5]: Current Event: BlockAppended, IsLimitExecutionTime: False. 
[2019-01-08 19:48:13.286 - Trace - FSM][5]: [StateEvent] BlockAppended 
[2019-01-08 19:48:13.286 - Trace - NodeStateFSM][5]: [NodeState] Leaving State BlockAppending 
[2019-01-08 19:48:13.287 - Trace - NodeStateFSM][5]: [NodeState] Entering State Catching 
[2019-01-08 19:48:13.287 - Trace - DPoS][5]: Lock number increment: 1 
[2019-01-08 19:48:13.287 - Warn - NetworkManager][5]: 127.0.0.1:6801 is sync source but not in sync state. 
[2019-01-08 19:48:13.288 - Debug - NetworkManager][5]: Catched up all peers. 
[2019-01-08 19:48:13.295 - Trace - TxRefBlockValidator][5]: Adding Canonical Hash be651f8094bc5c9e73f6d50ba31bece1942770ddaaf3bf7d4f470925cf6366be of height 1 
[2019-01-08 19:48:13.303 - Trace - BlockChain][5]: Finished rollback to 1 
[2019-01-08 19:48:13.303 - Trace - BlockExecutor][5]: Current Event: RollbackFinished, IsLimitExecutionTime: False. 
[2019-01-08 19:48:13.303 - Trace - FSM][5]: [StateEvent] RollbackFinished 
[2019-01-08 19:48:13.304 - Trace - NodeStateFSM][5]: [NodeState] Leaving State Catching 
[2019-01-08 19:48:13.304 - Trace - DPoS][5]: Lock number decrement: 0 
[2019-01-08 19:48:13.304 - Trace - ConsensusObserver][5]: ConsensusObserver completed. 
`

**Comment by EricBlack** [comment]
Close as fixed.
