### ISSUE TITLE
Multiple nodes rollback caused nodes stopped working

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#825]
## description
Run with 3 bp nodes, no customer transaction executed, running with only dpos transaction, nodes running with forked. And two of nodes tried to rollback and stopped at height 211, and other one node tried to rollback and throw exception, error message in below:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Kernel.Types.Transaction.TransactionTypeExtension.IsIndexingParentChainTransaction(Transaction transaction) in /home/aelf/github/AElf/AElf.Kernel.Types/Transaction/TransactionTypeExtension.cs:line 29
   at AElf.Miner.TxMemPool.TxHub.OnBranchRolledBack(List`1 blocks) in /home/aelf/github/AElf/AElf.Miner/TxMemPool/TxHub.cs:line 457
   at AElf.Miner.TxMemPool.TxHub.<Initialize>b__20_0(BranchRolledBack branch) in /home/aelf/github/AElf/AElf.Miner/TxMemPool/TxHub.cs:line 90
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
``` 

Three node running log are attached: 
[3bp-nodes-log.zip](https://github.com/AElfProject/AElf/files/2777537/3bp-nodes-log.zip)

**Comment by EricBlack** [comment]
Refactored not repro, will open new issue to follow if repro.
