### ISSUE TITLE
BuyResource/SellResource transaction failed due to NullReferenceException

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#952]
## Description
Testing resource contract with unit test, BuyResource/SellResource method executed failed due to System.NullReferenceException. Detail error message in below:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AElf.Sdk.CSharp.State.ActionInfo.Send(Object[] args)
   at lambda_method(Closure , Address , Address , UInt64 )
   at AElf.Contracts.Resource.ResourceContract.BuyResource(String resourceType, UInt64 paidElf)
```

**Comment by EricBlack** [comment]
Issue caused by allowance always equals zero no matter approved or not.

**Comment by EricBlack** [comment]
Close it due to fixed.
